### ISSUE TITLE
Error:Unable to create bitmap!

### ISSUE THREAD

**Issue by zhumengjia** [apache/cordova-plugin-camera#397] opened 2018-12-19 07:59 UTC
I use plug-ins to upload pictures.
cordova:7.1.0;
@ionic-native/camera:4.18;
cordova-plugin-camera:4.0.3;
On Android 7.1.2,select pictures from albums and convert them into base64 format. Error: unable to generate bitmaps!At the same time, I found that other Android phones with versions less than 8.0.0 have similar problems. It's no problem to take pictures with a camera. If you choose pictures from an album, you will report this error.

**Comment by jmdmao** [comment] 2019-02-03 03:17
Same problem.

**Comment by jcesarmobile** [comment] 2019-10-19 23:40
closing as duplicate of https://github.com/apache/cordova-plugin-camera/issues/360

**Closed by jcesarmobile** 2019-10-19 23:40 UTC
Labels: support
