### ISSUE TITLE
Moving DOM nodes in cordova app on return from native camera app

### ISSUE THREAD

**Issue by CodeWithOz** [apache/cordova-plugin-camera#537] opened 2019-12-12 15:38 UTC
# Bug Report

## Problem
There's a weird bug where returning from the device's camera causes some DOM nodes to briefly move down a few pixels and then 1-3 seconds later they're restored to their original position. I am not permitted to share gif/video showing this behavior. The problem only happens if I go back from the camera app. So if I take a picture I am redirected back to the app and there's no flicker/movement. As a result, I thought my `onError` callback would be of interest, but I have commented out everything inside it and this bug still manifests. I have looked at the CSS of the nodes that move and none of them is changed during this behavior. I have also looked at the CSS of their parents and still don't see a change, which is why I think it may be in plugin. It is _not_ the same thing happening in #511. My config for the plugin is:
```
    <plugin name="cordova-plugin-camera" spec="^4.1.0">
        <variable name="CAMERA_USAGE_DESCRIPTION" value=" " />
        <variable name="PHOTOLIBRARY_USAGE_DESCRIPTION" value=" " />
        <variable name="ANDROID_SUPPORT_V4_VERSION" value="27.+" />
    </plugin>
```

I really am at a loss as to what's causing it. This happens in Android but not in iOS. Any help will be appreciated.

### What is expected to happen?
No DOM nodes move around when I return from the camera.

### What does actually happen?
Returning from the device's camera causes some DOM nodes to briefly move down a few pixels and then 1-3 seconds later they're restored to their original position.

### Environment, Platform, Device

Cordova CLI 9.0.0
Cordova Android 8.1.0
Cordova Camera plugin 4.1.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by tryhardest** [comment] 2020-01-28 19:00
x 2

**Comment by DieOver** [comment] 2020-06-05 16:22
+1

**Comment by Mapiac** [comment] 2020-06-06 03:25
@DieOver this def. relates to status bar. Set as false in config.xml if the position shift seems to be about ~10 pixels or whatever the height is of the status bar.

**Comment by PieterVanPoyer** [comment] 2021-05-29 20:52
@CodeWithOz  is this issue still present. This seems to be more an issue of the statusbar plugin than of the camera plugin?
Maybe you should make an issue there and close this issue. When you add a reproduction issue, it will be easier to troubleshout.

**Comment by PieterVanPoyer** [comment] 2021-06-02 21:13
Closing as this issue seems to be more related to the statusbar.

**Closed by PieterVanPoyer** 2021-06-02 21:13 UTC
Labels: info-needed, platform: android
