### ISSUE TITLE
Plugin allows selection of .txt and .pdf but set on "MediaType.PICTURE" - Provider issue

### ISSUE THREAD

**Issue by etiks3** [apache/cordova-plugin-camera#635] opened 2020-07-23 07:31 UTC
# Bug Report

## Problem
We have implemented the plugin to upload only "MediaType.PICTURE" media type when selecting a picture form the gallery. However, some of our application users are able to select .txt files instead of pictures in the gallery. When we open the .txt file received the content is as follow:
`%2Fstorage%2Femulated%2F0%2FEpson%20iPrint%2Farr%C3%AAt%20de%20travail%20.pdf`
It sounds like the document was created from a scanner and available in the gallery as a .pdf. 
I don't know which device was used to send the file and i was not able to reproduce such a bug on my Android device.

### What is expected to happen?
The application we have built, allows user to send us pictures from their devices. We only authorized picture media type .jpeg or .png.

### What does actually happen?
On certain cases, users have been able to send .txt files, see Problem section above.

### Command or Code
Here is the code I've used to select from the gallery or from the camera:
 ```// Get event selector to device camera source type
            self.cameraSrcTypeSelector = function(e) {
                var eventSrc = e.target;
                var classListName = eventSrc.classList;
                var srcType;
                if (classListName.contains('camera')) {
                    srcType = Camera.PictureSourceType.CAMERA;
                } else if (classListName.contains('gallery')) {
                    srcType = Camera.PictureSourceType.SAVEDPHOTOALBUM;
                }
                pictureManager(srcType);
            };
 ```
Here are the camera options:
 ```          // Set all options for device camera
            function setCameraOptions(srcType) {
                var options = {
                    // Some common settings are 20, 50, and 100
                    quality: 50,
                    destinationType: Camera.DestinationType.DATA_URL,
                    // Dynamically set the picture source, Camera or photo gallery
                    sourceType: srcType,
                    encodingType: Camera.EncodingType.JPEG,
                    mediaType: Camera.MediaType.PICTURE,
                    allowEdit: false,
                    correctOrientation: true, //Corrects Android orientation quirks
                    direction: 0 // Ensure back camera is set by default
                }
                return options;
            };
 ```

### Environment, Platform, Device
Linux dev environment
Android and iOS devices (But I suspect it does only happen on Android devices)

### Version information
For example:
Cordova: 9.0.0 (cordova-lib@9.0.1)
Other Frameworks: Oracle JET 8.2.0
Operating System: Linux (Centos7)
Android Studio + XCode to emulate/simulate only

## Checklist

- [x ] I searched for existing GitHub issues
- [x ] I updated all Cordova tooling to most recent version
- [x ] I included all the necessary information above

**Comment by etiks3** [comment] 2020-08-03 12:12
After investigations, it seems that the fileprovider is causing the problem. I could not reproduce the issue but it seems that if I've used a external file provider to scan a document and select it with the camera plugin, .pdf and .txt files are allowed to be uploaded. We don't want that and restrict the camera plugin to be able to only upload .jpeg, .png. Is there a way to restrict the file provider in the device? Thanks for your answer

**Comment by etiks3** [comment] 2020-08-17 09:35
Hello any news on this thread? Thanks

**Comment by etiks3** [comment] 2020-08-20 13:02
> Hello any news on this thread? It sounds like the plugin allows providers to send .pdf or .txt. A reply would be appreciated, thanks.

**Comment by sboudouk** [comment] 2021-01-10 20:26
Any news on this ? I would like to allow pdf and images (png, jpeg) only. Despite setting the CameraType settings to pictures only, it keeps allowing me to upload everything.

Thanks.

**Comment by PieterVanPoyer** [comment] 2021-05-27 19:37
@sboudouk  en @etiks3  I am unable to replicate this issue. Seems to be working fine. When setting to select pictures only, I am only able to select images (bmp, gif, jpeg, png, ... ). 
I will test some more.
But without steps to reproduce and or a target device it will be difficult to troubleshoot this.

**Comment by PieterVanPoyer** [comment] 2021-07-01 20:13
I am closing this issue, because there is not enough information to start working on this.

**Closed by PieterVanPoyer** 2021-07-01 20:13 UTC
Labels: enhancement
