### ISSUE TITLE
app crashing in android 9 

### ISSUE THREAD

**Issue by enkc06** [apache/cordova-plugin-camera#434] opened 2019-03-20 16:32 UTC
# Bug Report

### What is expected to happen?
not to crash

### What does actually happen?
crash

### Version information

Installed platforms:
  android 8.0.0
  browser 5.0.4
  ios 4.5.5

Ionic:

   ionic (Ionic CLI)  : 4.12.0 
   Ionic Framework    : ionic-angular 3.9.4
   @ionic/app-scripts : 3.2.3

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 8.0.0, browser 5.0.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, (and 27 other plugins)

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 1.9.4
   ios-sim           : 7.0.0
   NodeJS            : v11.12.0
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by enkc06** [comment] 2019-03-21 15:15
Log when opening camera


03-21 11:06:12.193   883  1669 W ActivityManager: Scheduling restart of crashed service com.android.chrome/org.chromium.content.app.SandboxedProcessService0 in 1000ms
03-21 11:06:12.366   883  1669 W ActivityManager: Scheduling restart of crashed service com.android.chrome/org.chromium.chrome.browser.customtabs.CustomTabsConnectionService in 1000ms
03-21 11:06:13.572   883  1161 I ActivityManager: Start proc 27622:com.android.chrome/u0a87 for service com.android.chrome/org.chromium.chrome.browser.customtabs.CustomTabsConnectionService
03-21 11:06:15.202   883  5837 W ActivityManager: Scheduling restart of crashed service com.trunow.mobile/org.chromium.content.app.SandboxedProcessService0 in 18166ms
03-21 11:06:15.369   883  5837 W ActivityManager: Scheduling restart of crashed service com.android.chrome/org.chromium.chrome.browser.customtabs.CustomTabsConnectionService in 17998ms
03-21 11:06:15.646 26602 26602 E chromium: [ERROR:aw_browser_terminator.cc(113)] Renderer process (26921) crash detected (code -1).
03-21 11:06:15.668 26602 26602 E chromium: [ERROR:aw_browser_terminator.cc(81)] Render process (26921) kill (OOM or update) wasn't handed by all associated webviews, killing application.
03-21 11:06:24.416   883  1161 I ActivityManager: Start proc 27857:com.android.chrome/u0a87 for service com.android.chrome/org.chromium.chrome.browser.customtabs.CustomTabsConnectionService
03-21 11:06:24.508   883  1829 W ActivityManager: Scheduling restart of crashed service com.android.chrome/org.chromium.chrome.browser.customtabs.CustomTabsConnectionService in 1000ms
03-21 11:06:25.108   883  1161 I ActivityManager: Start proc 27983:com.android.chrome/u0a87 for service com.android.chrome/org.chromium.chrome.browser.customtabs.CustomTabsConnectionService
03-21 11:06:25.234   883  1815 W ActivityManager: Scheduling restart of crashed service com.android.chrome/org.chromium.chrome.browser.customtabs.CustomTabsConnectionService in 1000ms
03-21 11:06:26.255   883  1161 I ActivityManager: Start proc 28026:com.android.chrome/u0a87 for service com.android.chrome/org.chromium.chrome.browser.customtabs.CustomTabsConnectionService
03-21 11:06:26.363   883  2820 W ActivityManager: Scheduling restart of crashed service com.android.chrome/org.chromium.chrome.browser.customtabs.CustomTabsConnectionService in 4000ms
03-21 11:06:30.382   883  1161 I ActivityManager: Start proc 28045:com.android.chrome/u0a87 for service com.android.chrome/org.chromium.chrome.browser.customtabs.CustomTabsConnectionService
03-21 11:06:30.549   883  2820 W ActivityManager: Scheduling restart of crashed service com.android.chrome/org.chromium.chrome.browser.customtabs.CustomTabsConnectionService in 16000ms
03-21 11:07:38.920   883  1161 I ActivityManager: Start proc 28215:com.android.chrome/u0a87 for service com.android.chrome/org.chromium.chrome.browser.customtabs.CustomTabsConnectionService
03-21 11:07:39.033   883  2809 W ActivityManager: Scheduling restart of crashed service com.android.chrome/org.chromium.chrome.browser.customtabs.CustomTabsConnectionService in 15177ms

**Comment by enkc06** [comment] 2019-03-21 15:28
```
03-21 11:26:09.235   883  1331 W WindowManager: Token{f230728 ActivityRecord{8c3314b u0 com.oneplus.camera/.OPCameraServiceActivity t7830}} failed creating starting window
03-21 11:26:09.235   883  1331 W WindowManager: android.view.InflateException: Binary XML file line #35: Binary XML file line #35: Error inflating class <unknown>
03-21 11:26:09.235   883  1331 W WindowManager: Caused by: android.view.InflateException: Binary XML file line #35: Error inflating class <unknown>
03-21 11:26:09.235   883  1331 W WindowManager: Caused by: java.lang.reflect.InvocationTargetException
03-21 11:26:09.235   883  1331 W WindowManager: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
03-21 11:26:09.235   883  1331 W WindowManager: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
03-21 11:26:09.235   883  1331 W WindowManager: 	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
03-21 11:26:09.235   883  1331 W WindowManager: 	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
03-21 11:26:09.235   883  1331 W WindowManager: 	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:720)
03-21 11:26:09.235   883  1331 W WindowManager: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:788)
03-21 11:26:09.235   883  1331 W WindowManager: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
03-21 11:26:09.235   883  1331 W WindowManager: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
03-21 11:26:09.235   883  1331 W WindowManager: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
03-21 11:26:09.235   883  1331 W WindowManager: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
03-21 11:26:09.235   883  1331 W WindowManager: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
03-21 11:26:09.235   883  1331 W WindowManager: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
03-21 11:26:09.235   883  1331 W WindowManager: 	at com.android.internal.policy.DecorView.onResourcesLoaded(DecorView.java:1912)
03-21 11:26:09.235   883  1331 W WindowManager: 	at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2647)
03-21 11:26:09.235   883  1331 W WindowManager: 	at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2726)
03-21 11:26:09.235   883  1331 W WindowManager: 	at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2107)
03-21 11:26:09.235   883  1331 W WindowManager: 	at com.android.server.policy.PhoneWindowManager.addSplashScreen(PhoneWindowManager.java:4021)
03-21 11:26:09.235   883  1331 W WindowManager: 	at com.android.server.wm.SplashScreenStartingData.createStartingSurface(SplashScreenStartingData.java:56)
03-21 11:26:09.235   883  1331 W WindowManager: 	at com.android.server.wm.AppWindowContainerController$1.run(AppWindowContainerController.java:163)
03-21 11:26:09.235   883  1331 W WindowManager: 	at android.os.Handler.handleCallback(Handler.java:873)
03-21 11:26:09.235   883  1331 W WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-21 11:26:09.235   883  1331 W WindowManager: 	at android.os.Looper.loop(Looper.java:193)
03-21 11:26:09.235   883  1331 W WindowManager: 	at android.os.HandlerThread.run(HandlerThread.java:65)
03-21 11:26:09.235   883  1331 W WindowManager: 	at com.android.server.ServiceThread.run(ServiceThread.java:44)
03-21 11:26:09.235   883  1331 W WindowManager: Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 35: TypedValue{t=0x2/d=0x1010059 a=-1}
03-21 11:26:09.235   883  1331 W WindowManager: 	at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:965)
03-21 11:26:09.235   883  1331 W WindowManager: 	at android.content.res.TypedArray.getDrawable(TypedArray.java:949)
03-21 11:26:09.235   883  1331 W WindowManager: 	at android.view.View.<init>(View.java:5408)
03-21 11:26:09.235   883  1331 W WindowManager: 	at android.view.ViewGroup.<init>(ViewGroup.java:659)
03-21 11:26:09.235   883  1331 W WindowManager: 	at android.widget.FrameLayout.<init>(FrameLayout.java:92)
03-21 11:26:09.235   883  1331 W WindowManager: 	at android.widget.FrameLayout.<init>(FrameLayout.java:87)
03-21 11:26:09.235   883  1331 W WindowManager: 	at android.widget.FrameLayout.<init>(FrameLayout.java:82)
03-21 11:26:09.235   883  1331 W WindowManager: 	... 24 more
```

**Comment by hazems** [comment] 2019-03-22 01:15
What is the code that you use? And what is the Android device information?

**Comment by GedasGa** [comment] 2019-04-02 05:47
It's hard to tell the issue from your given information.

By the way, we support `node.js 6`, `8` and `10`. However, we don't support `v11.12.0`. If you are using the latest `node.js` features, be advised, that we only support the even-numbered releases (LTS) of `node.js`. Odd-numbered versions of `node.js` are not tested.

**Comment by vkeepe** [comment] 2019-04-29 22:10
@GedasGa I can confirm this is nothing to do with node.js version. I am using LTS version v10.15.1. Majority of my user on Android 9 are reporting crash while using camera. Looking into my Play Store crashes (stats) I can see Samsung has released this version on March 5th and my crash rate has increased on Android 9 the day it was released.

Let me know if we have any more detail on this issue.

**Comment by jpike88** [comment] 2019-05-02 10:14
This should be upgraded to CRITICAL, this breaks on all android 9 devices.

**Comment by reymonreyes** [comment] 2019-05-06 08:58
I hope an update of this plugin will be release soon. I'm still having issues on android 8/9. Using the master branch is not working either.

**Comment by RickLigas** [comment] 2019-05-24 16:14
I can concur what vkeepe has seen. My app had a crash rate of almost nothing (since Match 1 of 2018) then on Apr 23 2019 crashes increased, then on May 6 crashes increased dramatically. 97% are on Samsung Android 9 devices.

**Comment by jpike88** [comment] 2019-05-25 00:29
Can someone get at a stack trace?

**Comment by RickLigas** [comment] 2019-05-26 15:02
Is this of any help?

[trace of issue in question.txt](https://github.com/apache/cordova-plugin-camera/files/3220429/trace.of.issue.in.question.txt)

**Comment by hazems** [comment] 2019-05-27 06:29
I will try to grab Samsung Android 9 device to replicate it.
Can we have the sample code that can replicate this scenario @RickLigas @jpike88, thanks.

cc @janpio @jcesarmobile

**Comment by jpike88** [comment] 2019-05-27 11:52
```
import { Camera, CameraOptions } from '@ionic-native/camera';
const options: CameraOptions = {
			quality: 50,
			destinationType: Camera.DestinationType.DATA_URL,
			sourceType: Camera.PictureSourceType[isCamera ? 'CAMERA' : 'PHOTOLIBRARY'],
			allowEdit: false,
			encodingType: Camera.EncodingType.JPEG,
			targetHeight: 300,
			targetWidth: 400,
			saveToPhotoAlbum: false,
			correctOrientation: true
		};

		try {
			const photoData = `data:image/jpeg;base64,${await Camera.getPicture(options)}`;

			console.log(photoData);
		} catch (_) {
			// do nothing
		}
```

**Comment by jpike88** [comment] 2019-05-27 11:54
notable part of the stack trace:
```
at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:533)
       at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:433)
       at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:124)
       at android.app.Dialog.dismissDialog(Dialog.java:518)
       at android.app.Dialog.dismiss(Dialog.java:501)
       at org.apache.cordova.inappbrowser.InAppBrowser$5$1.onPageFinished(InAppBrowser.java:437)
```

**Comment by janpio** [comment] 2019-05-27 11:58
Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by jpike88** [comment] 2019-05-27 12:00
ill try to get at an actual device over the next few days, we're due for mobile update soon so ill sort it

**Comment by RickLigas** [comment] 2019-05-27 15:35
Unfortunately for our team, we can't reproduce it on our Samsung Android 9 devices. We don't see any issues at all. I have found a very odd series of interactions that guarantees a crash but I can't see very many, if any at all, users following it.  We have contact with one user who describes it as 'intermittent'.  In the next few days our support team should be able to provide more insight into what the user actually sees.

**Comment by RickLigas** [comment] 2019-05-28 14:28
Our team is having trouble reproducing the crash. Although none of our team's Android devices show the problem we continue to get crash reports. The trace is the same as the one I posted. We're investigating.

**Comment by jpike88** [comment] 2019-05-28 15:19
We're having trouble too reproducing it on the device that was problematic earlier, but it didn't get any updates since... god Android is such a PITA to debug

**Comment by RickLigas** [comment] 2019-05-28 18:01
Maybe I shouldn't be thinking out loud in this thread but our team is looking at how we handle permissions and we are starting to think these crashes are our problem. We may not be handling the case where a user has denied permissions and also set the 'Do not ask again' setting. 
Our crash may not be related to the camera plug in...

**Comment by reymonreyes** [comment] 2019-05-28 23:51
I've been testing this out on emulators(built-in and genymotion) and I'm getting mixed results. The issue is somehow intermittent.

**Comment by jpike88** [comment] 2019-05-29 02:11
Does a stack Trace give us an idea of the root cause

**Comment by hazems** [comment] 2019-06-04 17:51
Guys, I could not replicate this issue cc @janpio

**Comment by hazems** [comment] 2019-06-04 17:52
If someone can record a video with a sample of how to replicate this crash, this will be great, thank you.

**Comment by vkeepe** [comment] 2019-06-04 17:58
@hazems My issue I figured out was not related to camera. I am assuming rest are facing similar issues due to other plugins. 

I am using background mode plugin. Since android changed permission in Oreo and above it started the crash and camera was getting crashed due to the notification changes in Android.

I have fixed the issue by forking the original the work done:
https://github.com/vkeepe/cordova-plugin-background-mode.git

It is not yet merged in master so if anyone is using background plugin they might be facing same issues.

**Comment by RickLigas** [comment] 2019-06-04 18:03
We too are treating this as a permission issue and not a camera plugin issue. We still can't duplicate it.
Sorry for the message here in /cordova-plugin-camera.

**Comment by hazems** [comment] 2019-06-04 18:10
Not a problem so if it cannot be reproduced (or if it is not related to Camera plugin at all), please close this issue, thanks.

**Comment by RickLigas** [comment] 2019-06-04 21:21
For my part this is closed. But enkC06 will need to close this if he agrees.

**Closed** 2019-06-05 17:49 UTC
Labels: bug, platform: android

**Comment by abhinavkumar-utsa** [comment] 2019-08-25 22:30
This can definitely be reproduced and is happening on all Android 9 devices.

**Comment by timbru31** [comment] 2019-08-26 08:35
If so, please provide a MRE. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md
@abhinavkumar-utsa

**Comment by KreoDev** [comment] 2019-08-28 11:49
> @hazems My issue I figured out was not related to camera. I am assuming rest are facing similar issues due to other plugins.
> 
> I am using background mode plugin. Since android changed permission in Oreo and above it started the crash and camera was getting crashed due to the notification changes in Android.
> 
> I have fixed the issue by forking the original the work done:
> https://github.com/vkeepe/cordova-plugin-background-mode.git
> 
> It is not yet merged in master so if anyone is using background plugin they might be facing same issues.

This was a life saver. My camera was working on Android 7&8 but crushing on Android 9. Thank you very much

**Comment by QuentinIcky** [comment] 2019-08-28 15:00
@KreoDev how do you proceed to make it work ? For me it still failing

**Comment by KreoDev** [comment] 2019-08-28 20:17
cordova plugin rm cordova-plugin-background-mode
cordova plugin add https://github.com/vkeepe/cordova-plugin-background-mode
cordova platform rm android
cordova platform add android

That's all I did, and the camera stopped crushing my app on android 9 and android 7 & 8 also perfectly with the fix.

**Comment by jpike88** [comment] 2019-08-29 03:52
Can this issue also please be reopened, until it's actually resolved? It should be treated with a much higher severity.

**Comment by QuentinIcky** [comment] 2019-08-29 07:59
@KreoDev Thanks for your support, unfortunately it doesn't work for me :/

**Comment by Tioecomp** [comment] 2019-08-30 03:38
I'm having the same problem tried everthing possible

**Comment by ramzauchenna** [comment] 2019-09-13 17:40
it only works if i remove saveToPhotoAlbum: true for me

**Comment by jpike88** [comment] 2019-09-14 02:20
@janpio Can this issue also please be reopened, until it's actually resolved? It should be treated with a much higher severity. Is anyone maintaining this repo?

**Comment by arshad-sana** [comment] 2019-10-23 07:43
@KreoDev Solved my issue. Thank you so much.

**Comment by hemachandsai** [comment] 2019-11-20 12:09
@KreoDev Thanks buddy it solved my issue and a note:- no need to remove and platform android

**Comment by mirko77** [comment] 2019-11-20 12:34
Should it crash on Samsung devices with Android 9?

I have a Galaxy S5 with Android 9 (Lineage OS) and it is all good (no background mode) using version 4.1.0

**Comment by jpike88** [comment] 2019-11-20 13:12
Looks like an issue with how things are generated. To those who have problems, write a script that just wipes everything and installs things fresh each time. You won’t regret it

**Comment by mirko77** [comment] 2019-11-20 13:25
> Looks like an issue with how things are generated. To those who have problems, write a script that just wipes everything and installs things fresh each time. You won’t regret it

is it not what `cordova platform rm {platform}, cordova platform add {platform}` does?

**Comment by jpike88** [comment] 2019-11-20 13:26
Basically, but I like to go further and flush node modules and wipe my plugins folder, delete my platform folder and all. Sounds extreme but I host my own npm mirror anyway, and it practically guarantees any hooks run in the order they were designed to

**Comment by jpike88** [comment] 2019-11-20 13:28
`rm -rf node_modules;
rm -rf platforms;
rm -rf plugins;
rm -rf www;
mkdir www; `

**Comment by datazen** [comment] 2020-06-25 00:39
happens to me also with Android 9 devices and has for some time now.

**Comment by tryhardest** [comment] 2020-08-13 00:08
@jpike88 care to share that script?
