### ISSUE TITLE
Can't open camera on Android 11 with targetSdkVersion=30

### ISSUE THREAD

**Issue by kryops** [apache/cordova-plugin-camera#673] opened 2020-10-07 11:56 UTC
# Bug Report

### What is expected to happen?

The camera can be opened normally on Android 11 when building with `targetSdkVersion=30`.

### What does actually happen?

```
Error: You don't have a default camera.  Your device may not be CTS complaint.
```

## Information

The error comes from here: https://github.com/apache/cordova-plugin-camera/blob/0333d001c7c2df5418c2a344e275d3b43d99f2d8/src/android/CameraLauncher.java#L305

When removing the condition, the camera launches as expected.

Our current workaround is to stay on `targetSdkVersion=29`.

### Command or Code

```
camera.getPicture(onSuccess, onError, {
    quality: 50,
    destinationType: Camera.DestinationType.FILE_URI,
    sourceType: Camera.PictureSourceType.CAMERA,
    encodingType: Camera.EncodingType.JPEG,
    mediaType: Camera.MediaType.PICTURE,
    allowEdit: false,
    correctOrientation: true,
    targetWidth: 1920,
});
```

### Environment, Platform, Device

Android 11

### Version information

cordova 10.0.0
cordova-android 9.0.0
cordova-plugin-camera 5.0.0
cordova-plugin-androidx-adapter 1.1.1

```
<preference name="android-minSdkVersion" value="22" />
<preference name="android-targetSdkVersion" value="30" />
<preference name="AndroidXEnabled" value="true" />
```

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by Lampotrias** [comment] 2020-10-16 07:57
Promlem here:

```PackageManager mPm = activity.getPackageManager();
if (intent.resolveActivity(mPm) != null)
{
	cordova.startActivityForResult(this, intent, (CAMERA + 1) * 16 + returnType + 1);
}```
org/apache/cordova/camera/CameraLauncher.java

**Comment by Kristoffer93** [comment] 2020-10-20 11:58
I have the same problem.

**Comment by Fever905** [comment] 2021-02-22 19:08
Same issue here using a Pixel 4A 5G.  Switching back to 29 solves it for now.  Is this fix here ready?

**Comment by WuglyakBolgoink** [comment] 2021-05-31 12:07
@Fever905 after switching back to 29, can u install the app on android 11 devices? If I correct remember, the app will be not available in the google store. Or?

**Comment by PieterVanPoyer** [comment] 2021-06-01 15:23
@WuglyakBolgoink  normally the app would still be available for Android 11 devices in the playstore. It is just build with version 29. Android / Google will enforce new uploads to the playstore to be build with version 30 as of august (If I am correct).

**Comment by PieterVanPoyer** [comment] 2021-06-01 19:05
Same issue there: https://github.com/apache/cordova-plugin-camera/issues/734 

The issue according to @Ali54561 was:

>Yes I target Android Sdk 30.
>I am getting this error only on google pixel devices on which android 11 is installed. All other devices are working fine.

**Comment by WuglyakBolgoink** [comment] 2021-06-01 19:11
> @WuglyakBolgoink normally the app would still be available for Android 11 devices in the playstore. It is just build with version 29. Android / Google will enforce new uploads to the playstore to be build with version 30 as of august (If I am correct).

> Google will enforce new uploads to the playstore to be build with version 30 as of august (If I am correct)

yes, this is correct.

**Comment by Ali54561** [comment] 2021-06-03 14:21
I have downgraded my android target to 29 but same issue.

**Comment by Ali54561** [comment] 2021-06-04 16:02
I have downgraded my app from 29 to 30 and published it on playstore. Now It is not visible on android 11 devices.

![image_2021_06_04T15_53_56_356Z](https://user-images.githubusercontent.com/85111030/120830304-c7df1c80-c577-11eb-8d40-5234f1f0911e.png)

In screenshot, you can see I am trying to install my app on Google Pixel 3a XL(With Android 11) and it is saying this item is not compatible with your device.

**Comment by PieterVanPoyer** [comment] 2021-06-04 18:25
@Ali54561 can you add the link to the app on the playstore? I've got an Android 11 device and like to see it for myself. Because I've got apps build with target sdk 29 and they just appear to be compatibel with my device.

**Comment by Ali54561** [comment] 2021-06-07 08:58
Actually my clients are using android 11 and it is showing incompatible to their devices. so I have to publish my app with API level  11. Now it is available on play store with API level 11.

**Comment by NoelDeMartin** [comment] 2021-07-07 11:20
For anyone getting this issue, this has been solved in https://github.com/apache/cordova-plugin-camera/pull/684 and https://github.com/apache/cordova-plugin-camera/pull/739 but hasn't been merged yet. Until the fix is released, you can fix it by adding the following to the config.xml in your project (under `<platform name="android">`):

```xml
<config-file parent="/*" target="AndroidManifest.xml">
    <queries>
        <intent>
            <action android:name="android.media.action.IMAGE_CAPTURE" />
        </intent>
        <intent>
            <action android:name="android.intent.action.GET_CONTENT" />
        </intent>
    </queries>
</config-file>
```

If you're using `allowEdit`, you should also add `android.intent.action.PICK`.

**Comment by AdriVanHoudt** [comment] 2021-08-05 15:19
I can confirm that #684 fixes this issue for us

**Closed** 2021-08-09 11:57 UTC
Labels: platform: android, has-pr

**Comment by kevindanielr** [comment] 2021-12-13 17:33
Thanks for the help, I've been trying this and it hasn't worked for me. In the browser console it does not show me any error message when opening the camera or the gallery.

I would really appreciate your help.

**Comment by aymen110** [comment] 2022-09-26 08:27
For me the #684 does not resolve my problem.
I can't open the camera on pixel 6, the only solution that i found it was to add a bloc of try and catch 
in the file 'cameraLauncher' to be able to open the camera on pixel 6.
But this solution was not merged on the master branch.
Could someone help me here. 
i'm in sdk 30, with camera plugin version 5.0.3.
