### ISSUE TITLE
unable to create bitmap! error 

### ISSUE THREAD

**Issue by kotran88** [apache/cordova-plugin-camera#463] opened 2019-06-18 15:12 UTC
when I choose a picture from my gallery, it always goes to error saying unable to create bitmap!

what may be the problem? 

 const options : CameraOptions={
      quality:50,
      targetHeight:600,
      targetWidth:600,
      sourceType: this.camera.PictureSourceType.PHOTOLIBRARY,
      destinationType:this.camera.DestinationType.DATA_URL,
      encodingType:this.camera.EncodingType.JPEG,
      mediaType:this.camera.MediaType.PICTURE,
      saveToPhotoAlbum:true
    }
    const result= this.camera.getPicture(options).then(url=>{
      console.log("url is : "+url);
     

      
    },(err) => {
      window.alert(err);
      console.log("clickGallery err: "+err);
  })

**Comment by jcesarmobile** [comment] 2019-10-19 23:39
closing as duplicate of https://github.com/apache/cordova-plugin-camera/issues/360

**Closed by jcesarmobile** 2019-10-19 23:39 UTC
Labels: support
