### ISSUE TITLE
Cancelling the camera doesn't fire either onSuccess or onError when on iOS

### ISSUE THREAD

**Issue by moridianmess** [apache/cordova-plugin-camera#625] opened 2020-07-13 15:34 UTC
# Bug Report

### What is expected to happen?
When cancel is pushed within the camera plugin on iOS, the onError event is triggered. This works on Android.

### What does actually happen?
Neither the onError or onSuccess events are called.

### Command or Code
```
const options: any = {
	destinationType: 0,
	sourceType: 2,
	encodingType: 0,
	quality: 70,
	targetWidth: 768,
	targetHeight: 1024,
	allowEdit: false,
	correctOrientation: true,
	saveToPhotoAlbum: false,
};

this.camera
	.getPicture(options)
	.then(
		(imageData) => {
			// imageData is a base64 encoded string
		},
		(err) => {
			if (
				err == 'Camera cancelled.' ||
				err == 'No Image Selected'
			) {
				return;
			}
			console.log('camera error: ' + err);
		}
	)
	.catch((error) => {
		console.log('camera catch: ' + error);
	});
```

### Environment, Platform, Device
Ionic Angular (TS)
iOS
iPhone X / iPhone 11

### Version information
@ionic-angular@3.9.2
@ionic-native/camera@4.3.1
cordova-plugin-camera@4.1.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

Any help on this matter would be much appreciated.

**Comment by jcesarmobile** [comment] 2020-07-16 14:53
I can't reproduce using master branch, so will probably be fixed in next release

**Closed by jcesarmobile** 2020-07-16 14:53 UTC
