### ISSUE TITLE
Cordova-plugin-camera crashes app on android devices

### ISSUE THREAD

**Issue by lanadedstudio** [apache/cordova-plugin-camera#660] opened 2020-09-17 16:59 UTC
### Issue Type

- [x] Bug Report
- [ ] Feature Request
- [x] Support Question

## Description
The app crashes when the photo is captured. Error checked on Android 9 and 10, on IOS works well

### Command or Code

        navigator.camera.getPicture(this.onSuccess, this.onFail, {
            quality: 50,
            allowEdit: false,
            correctOrientation: true,
            allowEdit: true,
            destinationType: destinationType.DATA_URL
        });

### Version information

Cordova Packages:

    cli: 10.0.0
        common: 4.0.2
        create: 3.0.0
        lib: 10.0.0
            common: 4.0.2
            fetch: 3.0.0
            serve: 4.0.0

Project Installed Platforms:

    android: 8.1.0
    ios: 6.1.1

Project Installed Plugins:

    cordova-plugin-actionsheet: 2.3.3
    cordova-plugin-add-swift-support: 2.0.2
    cordova-plugin-biometric: 0.0.3
    cordova-plugin-camera: 4.0.3
    cordova-plugin-dialogs: 2.0.2
    cordova-plugin-file-transfer: 1.7.1
    cordova-plugin-file: 6.0.2
    cordova-plugin-fingerprint-aio: 3.0.1
    cordova-plugin-geolocation: 4.0.2
    cordova-plugin-keyboard: 1.2.0
    cordova-plugin-network-information: 2.0.2
    cordova-plugin-whitelist: 1.3.4

## Checklist

- [ ] I searched for already existing GitHub issues about this
- [ ] I updated all Cordova tooling to their most recent version
- [ ] I included all the necessary information above

**Comment by charlieshin** [comment] 2020-09-18 06:47
I have same problem here for version 4.2.

**Comment by erisu** [comment] 2020-09-18 07:24
@charlieshin @lanadedstudio can you both try with the latest camera plugin release?

I have just released a few hours ago version 5.0.0.

You should be able to use the latest just by removing and readding.
```
cordova plugin rm cordova-plugin-camera
cordova plugin add cordova-plugin-camera
```

**Comment by olidotjpeg** [comment] 2020-09-21 11:32
I am having a similar issue where when I take a picture with the new version `5.0.0` on Cordova 10 it just returns a `null`

**Comment by timbru31** [comment] 2020-09-21 11:46
Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by olidotjpeg** [comment] 2020-09-21 12:45
Just checked with a fresh cordova app, also fails there. If I have editing enabled, it says editing isn't allowed, and if I disable it it just sends out a `Error capturing image.` in the console.

**Comment by breautek** [comment] 2020-09-21 17:00
Can you test with `FILE_URI` instead of `DATA_URL` destination types?

In my experience, `DATA_URL` can cause memory issues and results in crashes on some devices, because representing high resolution images in a bae64 encoded string is rather inefficient. This is also noted in the [docs](https://github.com/apache/cordova-plugin-camera#module_Camera.DestinationType).

Alternatively, you could also try resizing the image using the `targetWidth` and `targetHeight` [camera options](https://github.com/apache/cordova-plugin-camera#cameracameraoptions--object).

>I am having a similar issue where when I take a picture with the new version 5.0.0 on Cordova 10 it just returns a null
>...
> Just checked with a fresh cordova app, also fails there. If I have editing enabled, it says editing isn't allowed, and if I disable it it just sends out a Error capturing image. in the console.

I'm not convinced this is the same issue as the OP described. You're describing an error case, where the OP is describing a crash (which I may be falsely interpreting that the app is closing unexpectedly). You may want to create a new issue so that we can track the issue you described independently.

**Comment by lanadedstudio** [comment] 2020-09-21 17:23
> @charlieshin @lanadedstudio, vocês dois podem tentar com o último lançamento do plugin de câmera?
> 
> Acabei de lançar há algumas horas a versão 5.0.0.
> 
> Você deve ser capaz de usar o mais recente apenas removendo e lendo.
> 
> ```
> cordova plugin rm cordova-plugin-camera
> cordova plugin add cordova-plugin-camera
> ```
> 
> Também devo observar que a versão mais recente também exigia **a** plataforma **Cordova-Android**`>= 9.0.0` .

I will test with the new version! TKS

**Comment by lanadedstudio** [comment] 2020-09-21 17:27
> @charlieshin @lanadedstudio can you both try with the latest camera plugin release?
> 
> I have just released a few hours ago version 5.0.0.
> 
> You should be able to use the latest just by removing and readding.
> 
> ```
> cordova plugin rm cordova-plugin-camera
> cordova plugin add cordova-plugin-camera
> ```
> 
> Sorry, I should also note that the latest release also required **Cordova-Android** platform `>= 9.0.0`.

I will test with the new version! TKS

I'm using the android version 8.1.0 because i'm building my app with Monaca and them requires this version... but i will try update android too

**Comment by olidotjpeg** [comment] 2020-09-22 07:13
@breautek We are already using FILE_URI. I will create a new repo to track these issues differently

**Comment by PieterVanPoyer** [comment] 2021-01-11 16:22
@lanadedstudio is this issue still happening with the latest released version? If not, feel free to close this issue.

**Comment by lanadedstudio** [comment] 2021-01-11 16:25
Yes, this continues to happen on some devices. Even with the updated plugin and using FILE_URI instead of DATA_URL.

**Comment by PieterVanPoyer** [comment] 2021-01-11 16:28
Are you able to provide a stacktrace of the crashes?

**Comment by lanadedstudio** [comment] 2021-01-11 16:35
After updating the plugin, the photos with the front camera are working, but the photos with the back camera still close the application. I removed the option to allow image editing. I also tested it with another camera app and it worked.

**Comment by PieterVanPoyer** [comment] 2021-01-11 16:38
Image editing is really discouraged in this plugin. 
![image](https://user-images.githubusercontent.com/33040889/104210929-c16acf80-5433-11eb-9930-d3e7df955a6b.png)

**Comment by rfernandoinfocast** [comment] 2021-03-08 20:22
hey guys: I was using version 4.2.0 and it was working well. Now I'm trying to install this version again and I'm not been able. What did happen to version 4.2.0 ?

**Comment by breautek** [comment] 2021-03-08 20:32
> hey guys: I was using version 4.2.0 and it was working well. Now I'm trying to install this version again and I'm not been able. What did happen to version 4.2.0 ?

Version 4.2.0 was never released because it contained https://github.com/apache/cordova-plugin-camera/pull/588 which broke some things on Android.

https://lists.apache.org/thread.html/rd4e20db0cc4e038f3ea9c14d29648fded38f7605359253c976a2e38d%40%3Cdev.cordova.apache.org%3E

**Comment by rfernandoinfocast** [comment] 2021-03-26 16:55
> > hey guys: I was using version 4.2.0 and it was working well. Now I'm trying to install this version again and I'm not been able. What did happen to version 4.2.0 ?
> 
> Version 4.2.0 was never released because it contained #588 which broke some things on Android.
> 
> https://lists.apache.org/thread.html/rd4e20db0cc4e038f3ea9c14d29648fded38f7605359253c976a2e38d%40%3Cdev.cordova.apache.org%3E

ok! thanks a lot.

**Comment by delvinwidjaja** [comment] 2021-04-23 07:52
Hi, is there any update on this issue ? I'm using the plugin v5.0.1 and the app still crashes after taking a photo with the back camera

**Comment by PieterVanPoyer** [comment] 2021-04-23 08:43
Are you able to provide a stacktrace of the crashes?

**Comment by delvinwidjaja** [comment] 2021-05-05 08:50
@PieterVanPoyer sorry for the late reply,  this is what I got from the log

```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=34, result=-1, data=null} to activity {de.myapp/de.myapp.MainActivity}: android.app.RecoverableSecurityException: de.myapp has no access to content://media/external/images/media/97
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4877)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4918)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2045)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7399)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
Caused by: android.app.RecoverableSecurityException: de.myapp has no access to content://media/external/images/media/97

````
Btw I tested it with the front camera and it logged the same error.

**Comment by breautek** [comment] 2021-05-05 13:44
> @PieterVanPoyer sorry for the late reply, this is what I got from the log
> 
> ```
> java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=34, result=-1, data=null} to activity {de.myapp/de.myapp.MainActivity}: android.app.RecoverableSecurityException: de.myapp has no access to content://media/external/images/media/97
>         at android.app.ActivityThread.deliverResults(ActivityThread.java:4877)
>         at android.app.ActivityThread.handleSendResult(ActivityThread.java:4918)
>         at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
>         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
>         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2045)
>         at android.os.Handler.dispatchMessage(Handler.java:107)
>         at android.os.Looper.loop(Looper.java:214)
>         at android.app.ActivityThread.main(ActivityThread.java:7399)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
> Caused by: android.app.RecoverableSecurityException: de.myapp has no access to content://media/external/images/media/97
> ```
> 
> Btw I tested it with the front camera and it logged the same error.
> 
> Cordova-plugin-camera : v.5.0.1
> cordova-android : 9.1.0
> tested on Android 10 Devices

This plugin likely doesn't handle API 29/30 changes to external storage. There should be potential two workarounds for the time being:

1. Target API 29 and add `requestLegacyExternalStorage` flag to the `AndroidManifest.xml` file

Adding this to your `config.xml` should work:

```xml
<edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application">
    <application android:requestLegacyExternalStorage="true" />
</edit-config>
```

**Note**: `requestLegacyExternalStorage` is ignored on API 30.

2. Fork this plugin and apply the PR https://github.com/apache/cordova-plugin-camera/pull/684
This solution should work for both API 29 and API 30.

**Comment by delvinwidjaja** [comment] 2021-05-06 08:11
@breautek thank you for your help. not it works as expected

**Comment by PieterVanPoyer** [comment] 2021-06-05 18:46
@lanadedstudio  is this issue still occuring with the latest Cordova and Cordova plugins versions?

**Comment by lanadedstudio** [comment] 2021-07-09 15:04
Yes, the problem persists

Cordova Version: 10.00
Cordova Plugin Camera Version: 5.0.1

I recently tested the error on smartphone models:

Smartphone Model: Moto G7 Play
OS Version: Android 10

Smartphone Model: Asus_X00TDB
OS Version: Android 9 

When I installed an external camera app (not the android camera) it worked normally.

**Comment by 21pg** [comment] 2021-08-13 06:40
> > @PieterVanPoyer sorry for the late reply, this is what I got from the log
> > ```
> > java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=34, result=-1, data=null} to activity {de.myapp/de.myapp.MainActivity}: android.app.RecoverableSecurityException: de.myapp has no access to content://media/external/images/media/97
> >         at android.app.ActivityThread.deliverResults(ActivityThread.java:4877)
> >         at android.app.ActivityThread.handleSendResult(ActivityThread.java:4918)
> >         at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
> >         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
> >         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
> >         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2045)
> >         at android.os.Handler.dispatchMessage(Handler.java:107)
> >         at android.os.Looper.loop(Looper.java:214)
> >         at android.app.ActivityThread.main(ActivityThread.java:7399)
> >         at java.lang.reflect.Method.invoke(Native Method)
> >         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
> >         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
> > Caused by: android.app.RecoverableSecurityException: de.myapp has no access to content://media/external/images/media/97
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Btw I tested it with the front camera and it logged the same error.
> > Cordova-plugin-camera : v.5.0.1
> > cordova-android : 9.1.0
> > tested on Android 10 Devices
> 
> This plugin likely doesn't handle API 29/30 changes to external storage. There should be potential two workarounds for the time being:
> 
> 1. Target API 29 and add `requestLegacyExternalStorage` flag to the `AndroidManifest.xml` file
> 
> Adding this to your `config.xml` should work:
> 
> ```
> <edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application">
>     <application android:requestLegacyExternalStorage="true" />
> </edit-config>
> ```
> 
> **Note**: `requestLegacyExternalStorage` is ignored on API 30.
> 
> 1. Fork this plugin and apply the PR [fix(android): supports sdk-30 package visibility #684](https://github.com/apache/cordova-plugin-camera/pull/684)
>    This solution should work for both API 29 and API 30.

will this work with cordova-android 10.0.0
As due to https://github.com/apache/cordova-android/issues/1250
I removed all edit-config and config-file tags from my config.xml

**Comment by breautek** [comment] 2021-08-13 12:24
> will this work with cordova-android 10.0.0

The PR mentioned in my comment has been merged. You can give it a test by installing from github. cordova-android@10 is required as it contains breaking changes making it incompatible with cordova-android@9.

**Comment by Quentin-Laplace** [comment] 2021-12-01 13:48
> 

I confirm that upgrading to 6.0.0 along side updgrading to cordova 10 and cordova-android 10 works in our project.

Nb : If you upgrade cordova from 8 to 10, don't forget to add  cordova-plugin-androidx-adapter plugin in your project, and verify gradle dependencies, in our case com.google.gms:google-services needs to be updated to 4.3.8.

**Comment by luizcantoni** [comment] 2022-05-13 02:30
Device: Motorola E7 with 4 GB RAM
Android: 10

My solution was install Open Camera and use this app to take photos from my Cordova App. 

Before Open Camera I was using the Motorola's Camera App that abruptly closes my app after I confirm a taken photo.

**Comment by jfoclpf** [comment] 2023-06-04 21:45
I'm having the same problem with cordova 11.1.0, the camera crashes the app while using back camera

I tried playing with options `quality`, `targetWidth` and `targetHeight` but it doesn't seem to solve

@delvinwidjaja can you tell me how do you get the stacktrace while testing the app on the device?

**Comment by sithwarrior** [comment] 2023-10-30 08:40
Im still seeing some instances of this error on Android devices, even with the latest release of this plugin and Cordova-android

`android.app.RecoverableSecurityException$1.createFromParcel`

```
Exception java.lang.RuntimeException:
  at android.app.ActivityThread.deliverResults (ActivityThread.java:5994)
  at android.app.ActivityThread.handleSendResult (ActivityThread.java:6033)
  at android.app.servertransaction.ActivityResultItem.execute (ActivityResultItem.java:67)
  at android.app.servertransaction.ActivityTransactionItem.execute (ActivityTransactionItem.java:45)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2574)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:226)
  at android.os.Looper.loop (Looper.java:313)
  at android.app.ActivityThread.main (ActivityThread.java:8762)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:604)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1067)
Caused by android.app.RecoverableSecurityException:
  at android.app.RecoverableSecurityException$1.createFromParcel (RecoverableSecurityException.java:197)
  at android.app.RecoverableSecurityException$1.createFromParcel (RecoverableSecurityException.java:194)
  at android.os.Parcel.readParcelableInternal (Parcel.java:4787)
  at android.os.Parcel.readParcelable (Parcel.java:4755)
  at android.os.Parcel.createExceptionOrNull (Parcel.java:3018)
  at android.os.Parcel.createException (Parcel.java:3007)
  at android.os.Parcel.readException (Parcel.java:2990)
  at android.database.DatabaseUtils.readExceptionFromParcel (DatabaseUtils.java:190)
  at android.database.DatabaseUtils.readExceptionFromParcel (DatabaseUtils.java:142)
  at android.content.ContentProviderProxy.delete (ContentProviderNative.java:629)
  at android.content.ContentResolver.delete (ContentResolver.java:2340)
  at android.content.ContentResolver.delete (ContentResolver.java:2306)
  at org.apache.cordova.camera.CameraLauncher.checkForDuplicateImage (CameraLauncher.java:1277)
  at org.apache.cordova.camera.CameraLauncher.cleanup (CameraLauncher.java:1242)
  at org.apache.cordova.camera.CameraLauncher.processResultFromCamera (CameraLauncher.java:626)
  at org.apache.cordova.camera.CameraLauncher.onActivityResult (CameraLauncher.java:877)
  at org.apache.cordova.CordovaInterfaceImpl.onActivityResult (CordovaInterfaceImpl.java:160)
  at org.apache.cordova.CordovaActivity.onActivityResult (CordovaActivity.java:375)
  at android.app.Activity.dispatchActivityResult (Activity.java:8951)
  at android.app.ActivityThread.deliverResults (ActivityThread.java:5987)

```

according to the Google Play Console, its happening on different devices on Android 13

**Closed** 2024-10-28 16:32 UTC
Labels: info-needed, platform: android
