### ISSUE TITLE
Apple rejects apps because of UIWebView reference

### ISSUE THREAD

**Issue by alfonsocuccaro** [apache/cordova-plugin-camera#594] opened 2020-05-06 22:18 UTC
# Bug Report

If I add this plugin to my app App Store will reject the app because this plugin contains references to UIWebView API. 
I have tried removing the plugins one by one, and seen that this is the plugin referencing UIWebView. There should be a way to make it reference to WKWebView

### Environment, Platform, Device
iOS

### Version information
**cordova-ios@5.1.1**
**cordova-plugin-camera@4.1.0 **

## Checklist

- [ x] I searched for existing GitHub issues
- [ x] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above

**Comment by timbru31** [comment] 2020-05-06 22:32
Duplicate of #556

**Closed by timbru31** 2020-05-06 22:32 UTC
