### ISSUE TITLE
After open the camera i get "Illegal Argument Exception".

### ISSUE THREAD

**Issue by jonapachanga** [apache/cordova-plugin-camera#689] opened 2020-11-18 14:21 UTC
# Bug Report
```
openCamera() {
    const options: CameraOptions = {
      quality: 100,
      destinationType: this.camera.DestinationType.DATA_URL,
      encodingType: this.camera.EncodingType.JPEG,
      mediaType: this.camera.MediaType.PICTURE
    };

    this.camera.getPicture(options).then((imageData) => {
      console.log(imageData);
    }, (err) => {
      console.log(err);
    });
  }
```
This is my code. It's very simple, I tried on Android 9 and Android 10, Also i played with the different CameraOptions but always i get "Illegal Argument Exception"
### What is expected to happen?

I have expected the camera open

### What does actually happen?

Throw the error `Illegal Argument Exception`

## Information
The followings are part of my package.json
```
"dependencies": {
    "@angular/common": "~9.1.6",
    "@angular/core": "~9.1.6",
    "@angular/forms": "~9.1.6",
    "@angular/platform-browser": "~9.1.6",
    "@angular/platform-browser-dynamic": "~9.1.6",
    "@angular/router": "~9.1.6",
    "@auth0/angular-jwt": "^5.0.1",
    "@capacitor/android": "^2.2.1",
    "@capacitor/core": "2.2.1",
    "@ionic-native/android-permissions": "^5.28.0",
    "@ionic-native/badge": "^5.27.0",
    "@ionic-native/base64": "^5.28.0",
    "@ionic-native/camera": "^5.29.0",
    "@ionic-native/core": "^5.0.7",
    "@ionic-native/device": "^5.27.0",
    "@ionic-native/diagnostic": "^5.27.0",
    "@ionic-native/downloader": "^5.28.0",
    "@ionic-native/file": "^5.27.0",
    "@ionic-native/file-chooser": "^5.27.0",
    "@ionic-native/file-opener": "^5.27.0",
    "@ionic-native/file-path": "^5.27.0",
    "@ionic-native/file-picker": "^5.27.0",
    "@ionic-native/file-transfer": "^5.27.0",
    "@ionic-native/image-picker": "^5.27.0",
    "@ionic-native/local-notifications": "^5.27.0",
    "@ionic-native/media": "^5.27.0",
    "@ionic-native/media-capture": "^5.27.0",
    "@ionic-native/push": "^5.27.0",
    "@ionic-native/social-sharing": "^5.27.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic-native/video-editor": "^5.28.0",
    "@ionic/angular": "^5.0.0",
    "aws-sdk": "^2.739.0",
    "com-badrit-base64": "^0.2.0",
    "cordova-plugin-android-permissions": "^1.0.2",
    "cordova-plugin-badge": "^0.8.8",
    "cordova-plugin-camera": "^5.0.1",
    "cordova-plugin-device": "^2.0.3",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-file-opener2": "^3.0.4",
    "cordova-plugin-file-transfer": "^1.7.1",
    "cordova-plugin-filechooser": "^1.2.0",
    "cordova-plugin-filepath": "^1.5.8",
    "cordova-plugin-filepicker": "^1.1.6",
    "cordova-plugin-local-notification": "^0.9.0-beta.2",
    "cordova-plugin-media": "^5.0.3",
    "cordova-plugin-media-capture": "^3.0.3",
    "cordova-plugin-telerik-imagepicker": "^2.3.3",
    "cordova-plugin-video-editor": "^1.1.3",
    "cordova-plugin-x-socialsharing": "^5.6.8",
    "cordova.plugins.diagnostic": "^6.0.2",
    "date-fns": "^2.15.0",
    "es6-promise-plugin": "^4.2.2",
    "google-libphonenumber": "^3.2.11",
    "integrator-cordova-plugin-downloader": "^1.1.0",
    "ionic2-calendar": "^0.6.6",
    "jetifier": "^1.6.6",
    "jssha": "^3.1.1",
    "ng2-currency-mask": "^9.0.2",
    "phonegap-plugin-multidex": "^1.0.0",
    "phonegap-plugin-push": "^2.3.0",
    "rxjs": "~6.5.1",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.5",
    "@angular/cli": "~9.1.5",
    "@angular/compiler": "~9.1.6",
    "@angular/compiler-cli": "~9.1.6",
    "@angular/language-service": "~9.1.6",
    "@capacitor/cli": "2.2.1",
    "@ionic/angular-toolkit": "^2.1.1",
    "@types/google-libphonenumber": "^7.4.19",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/jssha": "^2.0.0",
    "@types/node": "^12.12.54",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.8.3"
  },
  "description": "An Ionic project"
}
```

### Environment, Platform, Device
I am running Ionic CLI 6.10.1 with Capacitor - Angular CLI 9.0.6

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by naitikpatel1990** [comment] 2020-11-18 17:28
Getting same issue. Tried every possible way for it. But seems crashed inn native code. Please Help us in to that.

Thank you

**Comment by breautek** [comment] 2020-11-18 17:32
Can someone let me know if the error goes away if `<preference name="android-targetSdkVersion" value="28" />` is used?

Note that targeting API 28 won't be google play store compliant but will tell us if this is a problem introduced by an android API change.

**Comment by naitikpatel1990** [comment] 2020-11-18 17:39
@breautek 

After add that still getting same error.

**Comment by breautek** [comment] 2020-11-18 17:50
Thanks for trying.

We'll probably will require a [Sample Reproduction App](https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md) to move this issue along.

**Comment by jonapachanga** [comment] 2020-11-24 13:00
Hi, I created a Sample Reproduction App as suggested by @breautek and to my surprise the plugin works fine. The only difference is the version of the plugin, in my project i have:
```
"@ionic-native/camera": "^5.29.0"
"cordova-plugin-camera": "^5.0.1"
```
And the new one
```
"@ionic-native/camera": "^5.30.0"
"cordova-plugin-camera": "^5.0.1"
```
i updated my project but it still doesn't work. Are there any plugin what interfere with camera plugin?

the strange thing is that when I use the plugin to select an image from the gallery it works fine

**Comment by naitikpatel1990** [comment] 2021-01-05 14:16
@jonapachanga 

I suspect that latest plugin is getting same error with ionic 5 version.

I do have same plugin in ionic 4 working fine.

Can you confirm on that?

**Comment by PieterVanPoyer** [comment] 2021-01-08 19:27
@jonapachanga  can you add a stacktrace? I am not sure if it is a Javascript exception or a native plugin exception.

**Comment by naitikpatel1990** [comment] 2021-01-09 05:45
@PieterVanPoyer 

Might be following might help to identified issue:

<img width="1680" alt="Screenshot 2021-01-09 at 11 11 54 AM" src="https://user-images.githubusercontent.com/4089997/104084281-bebd7e00-526b-11eb-9829-60e7e22c44ff.png">


FYI: Permission for camera is given manually. First time camera permission was not asked and app is just crashed.  Something really missing or crashed.

**Comment by naitikpatel1990** [comment] 2021-01-09 11:39
Hey,

I fixed by changed some code in CameraLauncher.java file but it's not proper as i did hardcoded there.

in `public void takePicture(int returnType, int encodingType)` method  has following code:

```
this.imageUri = new CordovaUri(FileProvider.getUriForFile(cordova.getActivity(),
                applicationId + ".provider",
                photo));
```
                
             here somehow in ionic 5 `applicationId` got not found and throwing that error.
             
     so for now i hard coded like following:
     
   ```
  this.imageUri = new CordovaUri(FileProvider.getUriForFile(cordova.getActivity(),
                 "my.application.packgeID.provider", // my.application.packgeID is my app package id 
                photo));
```
                
              and bingo it's working. 
              
              But we need proper solution to grab package id there it's not dynamic for now. Thank you

**Comment by PieterVanPoyer** [comment] 2021-01-09 19:40
Strange. Normally there is BuildConfig.class generated. (Not the one under org.apache.cordova)

The applicationId is read from the BuildConfig in the CameraLauncer.
![image](https://user-images.githubusercontent.com/33040889/104107178-b04a8300-52ba-11eb-8ac4-1123502bab19.png)

![image](https://user-images.githubusercontent.com/33040889/104107202-db34d700-52ba-11eb-9619-fb838c3dd4e8.png)

**Comment by naitikpatel1990** [comment] 2021-01-13 11:37
@PieterVanPoyer 

that can be happened and missed packageID in my code either of following reasons:

1) I did changed my packageID and uninstall and install platform in ionic after that or

2) we are on IONIC 5 where it was not working. FYI: in ionic 4 with same plugin i can able to open camera without any changes in plugin what i did above.

Above might help you to identified issue.

**Comment by PieterVanPoyer** [comment] 2021-01-13 12:46
@naitikpatel1990 can you search for a BuildConfig class in your project? Like in my screenshot? Is it present in your project after building or during debugging?

**Comment by PieterVanPoyer** [comment] 2021-05-19 18:58
Is this issue still present. If it is not reproducable in a plain Cordova app, we won't be able to help.

If the issue is solved, please close it.

**Comment by PieterVanPoyer** [comment] 2021-05-26 20:59
@naitikpatel1990 Is this issue still present. If it is not reproducable in a plain Cordova app, we won't be able to help and need to close this issue.

If the issue is solved, please close it.

**Comment by naitikpatel1990** [comment] 2021-05-31 07:49
@PieterVanPoyer  

Issue is not opened by me so i can't close it.

Regarding issue i gave all possible ways i tried and it seems working for me. So not gonna make sample app and integrate as too much overloaded with other tasks for now.

**Comment by PieterVanPoyer** [comment] 2021-05-31 08:01
@naitikpatel1990 thanks for the info. Indeed you did not open this issue.

@jonapachanga Is this issue still present with the latest camera version (v5.0.2)? If it is not reproducable in a plain Cordova app, we won't be able to help and need to close this issue.

If the issue is solved, please close it.

**Comment by PieterVanPoyer** [comment] 2021-06-01 20:14
Issue is being closed due to missing reproduction cordova app.

**Closed by PieterVanPoyer** 2021-06-01 20:14 UTC
Labels: info-needed

**Comment by MattSynaptic** [comment] 2021-07-21 17:40
> Hey,
> 
> I fixed by changed some code in CameraLauncher.java file but it's not proper as i did hardcoded there.
> 
> in `public void takePicture(int returnType, int encodingType)` method has following code:
> 
> ```
> this.imageUri = new CordovaUri(FileProvider.getUriForFile(cordova.getActivity(),
>                 applicationId + ".provider",
>                 photo));
> ```
> 
> here somehow in ionic 5 `applicationId` got not found and throwing that error.
> 
> so for now i hard coded like following:
> 
> ```
> this.imageUri = new CordovaUri(FileProvider.getUriForFile(cordova.getActivity(),
>                  "my.application.packgeID.provider", // my.application.packgeID is my app package id 
>                 photo));
> ```
> 
> and bingo it's working.
> 
> But we need proper solution to grab package id there it's not dynamic for now as i don't know it's ionic 5 issue or plugin code issue till now. :)
> 
> Thank you

This worked for me but I figured out if you do this it will resolve it without having to hard-code the applicationId in:

```
    public boolean execute(String action, JSONArray args, CallbackContext callbackContext) throws JSONException {
        this.callbackContext = callbackContext;

        //Adding an API to CoreAndroid to get the BuildConfigValue
        //This allows us to not make this a breaking change to embedding
        // BROKEN: this.applicationId = (String) BuildHelper.getBuildConfigValue(cordova.getActivity(), "APPLICATION_ID");
        // BROKEN: this.applicationId = preferences.getString("applicationId", this.applicationId);
        this.applicationId = cordova.getActivity().getPackageName(); // ADDED
```
