### ISSUE TITLE
Camera is not opening on Sony Xperia(J8210) only on other devices its working.

### ISSUE THREAD

**Issue by adeel399** [apache/cordova-plugin-camera#817] opened 2022-11-23 18:40 UTC
# Bug Report
Camera is not opening on Sony Xperia(J8210) only on other devices its working.
### What is expected to happen?
Camera should open smothly on device

### What does actually happen?

camera is not opening without any error

## Information

{
  "name": "sezzsoapp",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "~11.2.0",
    "@angular/core": "~11.2.0",
    "@angular/forms": "~11.2.0",
    "@angular/platform-browser": "~11.2.0",
    "@angular/platform-browser-dynamic": "~11.2.0",
    "@angular/router": "~11.2.0",
    "@awesome-cordova-plugins/android-permissions": "^5.37.1",
    "@awesome-cordova-plugins/camera": "^5.37.1",
    "@awesome-cordova-plugins/core": "^5.37.1",
    "@awesome-cordova-plugins/media-capture": "^5.37.1",
    "@awesome-cordova-plugins/social-sharing": "^5.40.0",
    "@capacitor/android": "^3.0.0",
    "@capacitor/core": "3.0.0",
    "@capacitor/ios": "^3.0.0",
    "@ionic-native/barcode-scanner": "^5.36.0",
    "@ionic-native/clipboard": "^5.35.0",
    "@ionic-native/core": "^5.33.1",
    "@ionic-native/downloader": "^5.33.1",
    "@ionic-native/file": "^5.33.1",
    "@ionic-native/file-path": "^5.36.0",
    "@ionic-native/ftp": "^5.36.0",
    "@ionic-native/in-app-browser": "^5.33.1",
    "@ionic-native/onesignal": "^5.31.1",
    "@ionic-native/preview-any-file": "^5.36.0",
    "@ionic-native/social-sharing": "^5.33.1",
    "@ionic-native/streaming-media": "^5.36.0",
    "@ionic-native/stripe": "^5.33.1",
    "@ionic-native/video-editor": "^5.36.0",
    "@ionic/angular": "^5.5.2",
    "@ionic/cordova-builders": "^6.1.0",
    "cordova-plugin-android-support-v4": "^21.0.1",
    "cordova-plugin-androidx": "^3.0.0",
    "cordova-plugin-androidx-adapter": "^1.1.3",
    "exif-js": "^2.3.0",
    "mux-embed": "^4.1.1",
    "ngx-pinch-zoom": "^2.6.2",
    "npm": "^6.14.13",
    "plyr": "^3.6.8",
    "recursive-readdir": "^2.2.2",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "video.js": "^7.15.4",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.1102.18",
    "@angular/cli": "^11.1.4",
    "@angular/compiler": "^11.2.14",
    "@angular/compiler-cli": "^11.2.14",
    "@angular/language-service": "~11.2.0",
    "@capacitor/cli": "3.0.0",
    "@ionic/angular-toolkit": "^3.1.0",
    "@types/jasmine": "~3.6.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "@typescript-eslint/eslint-plugin": "4.16.1",
    "@typescript-eslint/parser": "4.16.1",
    "com-darryncampbell-cordova-plugin-intent": "^2.2.0",
    "cordova-android": "^9.1.0",
    "cordova-clipboard": "^1.3.0",
    "cordova-plugin-android-permissions": "^1.1.2",
    "cordova-plugin-camera": "^5.0.3",
    "cordova-plugin-chooser": "^1.3.2",
    "cordova-plugin-compat": "^1.2.0",
    "cordova-plugin-device": "2.0.2",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-ftp": "^1.2.1",
    "cordova-plugin-inappbrowser": "^5.0.0",
    "cordova-plugin-ionic-keyboard": "^2.0.5",
    "cordova-plugin-ionic-webview": "^4.0.0",
    "cordova-plugin-media-capture": "^3.0.3",
    "cordova-plugin-preview-any-file": "^0.2.9",
    "cordova-plugin-splashscreen": "5.0.2",
    "cordova-plugin-statusbar": "2.4.2",
    "cordova-plugin-streaming-media": "^2.3.0",
    "cordova-plugin-stripe": "^1.5.3",
    "cordova-plugin-video-editor": "^1.1.3",
    "cordova-plugin-whitelist": "1.3.3",
    "cordova-plugin-x-socialsharing": "^6.0.3",
    "es6-promise-plugin": "^4.2.2",
    "eslint": "^7.6.0",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jsdoc": "30.7.6",
    "eslint-plugin-prefer-arrow": "1.2.2",
    "integrator-cordova-plugin-downloader": "^1.1.0",
    "jasmine-core": "~3.7.1",
    "jasmine-spec-reporter": "~5.0.0",
    "jetifier": "^2.0.0",
    "karma": "~6.3.2",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "onesignal-cordova-plugin": "^3.2.0",
    "phonegap-plugin-barcodescanner": "^8.1.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "typescript": "^4.0.8"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-media-capture": {},
      "cordova-plugin-ionic-webview": {
        "ANDROID_SUPPORT_ANNOTATIONS_VERSION": "27.+"
      },
      "cordova-plugin-inappbrowser": {},
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-file": {},
      "integrator-cordova-plugin-downloader": {},
      "phonegap-plugin-barcodescanner": {
        "ANDROID_SUPPORT_V4_VERSION": "27.+"
      },
      "cordova-plugin-android-permissions": {},
      "cordova-clipboard": {},
      "cordova-plugin-preview-any-file": {},
      "cordova-plugin-streaming-media": {},
      "cordova-plugin-video-editor": {},
      "cordova-plugin-camera": {
        "ANDROID_SUPPORT_V4_VERSION": "27.+"
      },
      "cordova-plugin-chooser": {},
      "cordova-plugin-stripe": {},
      "cordova-plugin-x-socialsharing": {},
      "onesignal-cordova-plugin": {}
    },
    "platforms": [
      "android"
    ]
  }
}
above is my package.json 

i am using ionic 6 with cordova

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by adeel399** [comment] 2022-11-30 15:06
Anuone plz respond

**Comment by breautek** [comment] 2022-12-01 16:19
We can't really provide much input if frameworks are in play as the may change how things work.

I would suggest trying to create a sample application without the use of frameworks to see if you can reproduce your issue. If you cannot reproduce your issue in the sample app, then it suggests the problem within the framework code.

And if you can reproduce your issue in the sample application.... if it only occurs on that specific device, it suggests that the selected Camera application on that device is doing something not standard and is not compatible to be used as an Intent, which is something that Cordova cannot resolve.

**Comment by breautek** [comment] 2022-12-12 21:04
If there is no default app for camera, then the phone is suppose to prompt the user to select an app, with a "Use" and a "Use Always" option. If the user selects the Always option, the device is suppose to mark that app as the app to use for the camera intent.

#673 does solve the similar issue and the change is released in v6 of this plugin, but the OP is still on 5.x.

Closing as not a bug... I suggest trying to use cordova-plugin-camera@6 for API 30 support.

**Closed by breautek** 2022-12-12 21:04 UTC
