### ISSUE TITLE
No camera permission in Android app.

### ISSUE THREAD

**Issue by ankitjainOfficial** [apache/cordova-plugin-camera#419] opened 2019-01-31 15:07 UTC
In my app, I use https://github.com/dpa99c/cordova-diagnostic-plugin for checking permissions before invoking `camera.getPictures` method. When I'm trying to check for camera permission, it is sending me to the app settings page, to enable camera. But, it does not show camera in the list of permissions. 

On digging a little deeper, I find that the AndroidManifest.xml does not have the <uses-permission> for `android.permission.CAMERA`. 

Can anybody please let me know, what is the best way to get that permission applied, or if I'm attempting to do something incorrect.

`ionic info`

```
Ionic:

   ionic (Ionic CLI)  : 4.5.0 (/Users/ankit/.nvm/versions/node/v7.10.0/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, ios 4.5.4
   Cordova Plugins       : cordova-plugin-ionic-webview 3.1.1, (and 26 other plugins)

System:

   Android SDK Tools : 26.1.1 (/users/ankit/dev-tools/android-sdk-macosx)
   ios-deploy        : 1.9.2
   ios-sim           : 6.1.2
   NodeJS            : v7.10.0 (/Users/ankit/.nvm/versions/node/v7.10.0/bin/node)
   npm               : 5.4.2
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61
```

`cordova plugins`

```
branch-cordova-sdk 3.1.5 "branch-cordova-sdk"
call-number 0.0.2 "Cordova Call Number Plugin"
cordova-clipboard 1.2.1 "Clipboard"
cordova-custom-config 5.0.3 "cordova-custom-config"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-apprate 1.4.0 "AppRate"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-crop 0.1.0 "CropPlugin"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-email-composer 0.8.15 "EmailComposer"
cordova-plugin-file 5.0.0 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-googlemaps 2.5.0 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-ionic-webview 3.1.1 "cordova-plugin-ionic-webview"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-safariviewcontroller 1.5.4 "SafariViewController"
cordova-plugin-screen-orientation 3.0.1 "Screen Orientation"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.4 "SocialSharing"
cordova-sms-plugin 0.1.13 "Cordova SMS Plugin"
cordova.plugins.diagnostic 4.0.10 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.2.2 "Launch Navigator"
```

I tried adding this code in config.xml, but the build fails, with AAPT2 error.
```
        <config-file mode="merge" parent="/*" target="AndroidManifest.xml">
            <uses-permission android:name="android.permission.CAMERA" />
            <uses-feature android:name="android.hardware.camera" />
            <uses-feature android:name="android.hardware.camera.autofocus" />
        </config-file>
```

Let me know, if any detailed info is required. Thanks.

**Comment by ankitjainOfficial** [comment] 2019-01-31 15:16
And here is the `AndroidManifest.xml`

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<manifest android:hardwareAccelerated="true" android:versionCode="60200" android:versionName="6.2.0" package="com.test.app" xmlns:android="http://schemas.android.com/apk/res/android">
  <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true"/>
  <uses-permission android:name="android.permission.INTERNET"/>
  <uses-permission android:name="android.permission.CALL_PHONE"/>
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
  <uses-permission android:name="android.permission.GET_ACCOUNTS"/>
  <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
  <uses-permission android:name="android.permission.SEND_SMS"/>
  <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
  <uses-permission android:name="android.permission.BLUETOOTH"/>
  <application android:hardwareAccelerated="true" android:icon="@mipmap/icon" android:label="@string/app_name" android:supportsRtl="true">
    <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale" android:label="@string/activity_name" android:launchMode="singleTask" android:name="MainActivity" android:theme="@android:style/Theme.DeviceDefault.NoActionBar" android:windowSoftInputMode="adjustResize">
      <intent-filter android:label="@string/launcher_name">
        <action android:name="android.intent.action.MAIN"/>
        <category android:name="android.intent.category.LAUNCHER"/>
      </intent-filter>
      <intent-filter android:name="io.branch.sdk.UriScheme">
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:scheme="test"/>
      </intent-filter>
      <intent-filter android:name="io.branch.sdk.AppLink" android:autoVerify="true">
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:host="fleb.app.link" android:scheme="https"/>
        <data android:host="fleb-alternate.app.link" android:scheme="https"/>
      </intent-filter>
    </activity>
    <activity android:name="com.soundcloud.android.crop.CropImageActivity"/>
    <provider android:authorities="${applicationId}.provider" android:exported="false" android:grantUriPermissions="true" android:name="org.apache.cordova.camera.FileProvider">
      <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/camera_provider_paths"/>
    </provider>
    <provider android:authorities="${applicationId}.provider" android:exported="false" android:grantUriPermissions="true" android:name="de.appplant.cordova.emailcomposer.Provider">
      <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/emailcomposer_provider_paths"/>
    </provider>
    <provider android:authorities="${applicationId}.sharing.provider" android:exported="false" android:grantUriPermissions="true" android:name="nl.xservices.plugins.FileProvider">
      <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/sharing_paths"/>
    </provider>
    <meta-data android:name="com.google.android.geo.API_KEY" android:value="AIzaSyB"/>
    <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version"/>
    <meta-data android:name="io.branch.sdk.BranchKey" android:value="key_live_"/>
    <meta-data android:name="io.branch.sdk.TestMode" android:value="false"/>
    <uses-library android:name="org.apache.http.legacy" android:required="false"/>
    <receiver android:enabled="true" android:name="nl.xservices.plugins.ShareChooserPendingIntent">
      <intent-filter>
        <action android:name="android.intent.action.SEND"/>
      </intent-filter>
    </receiver>
    <receiver android:name="io.branch.referral.InstallListener" android:exported="true">
      <intent-filter>
        <action android:name="com.android.vending.INSTALL_REFERRER"/>
      </intent-filter>
    </receiver>
  </application>
  <uses-sdk android:minSdkVersion="19" android:targetSdkVersion="27"/>
  <uses-feature android:name="android.hardware.telephony" android:required="false"/>
  <uses-feature android:name="android.hardware.location.gps"/>
  <uses-feature android:glEsVersion="0x00020000" android:required="true"/>
  <uses-feature android:name="android.hardware.location"/>
</manifest>
```

**Comment by RidClick** [comment] 2019-02-13 17:18
Same issue here, 
when installing the plugin the camera permission is not added automatically and when you put it in the config.xml it gives AAPT2 error.

**Comment by SergioEnrique** [comment] 2019-03-21 03:29
I have the same issue for camera plugin 4.0.3

**Comment by Mapiac** [comment] 2019-06-22 21:06
@SergioEnrique have you tried on latest Cordova?

**Comment by Arieru** [comment] 2019-07-29 12:29
I have the same issue. What I always do to make it work is to add the permission:
`<uses-permission android:name="android.permission.CAMERA"/>`
manually to the AndroidManifest.xml which I really think is not the right way to do it.
Does anyone already has a solution for this?

**Comment by LordPachelbel** [comment] 2019-10-15 19:15
If you use https://www.npmjs.com/package/cordova-plugin-settings-hook then you can define the permissions in your app's `config.xml`.

**Comment by breautek** [comment] 2019-10-17 02:46
Camera permissions is not necessary for this plugin because we don't use the camera APIs directly. Instead we use the Camera intent, which uses the system's camera app.

> Note: If you are using the camera by invoking an existing camera app, your application does not need to request this permission.

https://developer.android.com/guide/topics/media/camera#manifest

The camera permission is required if you use the `Camera` API directly which would allow you to control the camera without the user really knowing and this plugin does not use those APIs.

**Comment by jasonandress** [comment] 2019-10-31 18:34
Without this permission for me it doesn't work. I have to manually add this through the edit config in the config xml

<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

**Comment by AmrAlmagic** [comment] 2020-01-10 20:39
@ankitjainOfficial 
I also faced this issue.
Are you solve it?

**Comment by ankitjainOfficial** [comment] 2020-01-15 09:48
@AmrAlmagic It's been a while, I think the solution was:

Adding this to your config.xml

```
        <custom-config-file parent="/*" target="AndroidManifest.xml">
            <uses-permission android:name="android.permission.CAMERA" />
            <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
        </custom-config-file>
```

And install this [package](https://github.com/dpa99c/cordova-custom-config#readme)


I didn't need to make any changes to AndroidManifest directly.

If everything works, you should see the following in `platforms/android/app/src/main/AndroidManifest.xml`:

```
<uses-permission android:name="android.permission.CAMERA"/>
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
```

**Comment by AmrAlmagic** [comment] 2020-01-30 16:56
@ankitjainOfficial sorry for the late response 
first, thanks for your reply
I tried to add 

>         <custom-config-file parent="/*" target="AndroidManifest.xml">
>             <uses-permission android:name="android.permission.CAMERA" />
>             <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
>         </custom-config-file>

get some errors while building apk and removed them.
but when add cordova-custom-config package solved from the second launch!.

**Comment by JaymerJaymer** [comment] 2020-02-13 22:33
important to note that going this <custom-config-file...> route DOES NOT WORK WITH BUILD.PHONEGAP
per author: https://github.com/dpa99c/cordova-custom-config#remote-build-environments

**Comment by jcesarmobile** [comment] 2020-06-26 14:53
As breautek said, this plugin doesn't need Camera permission. What you are trying to do has nothing to do with the plugin and it's not a bug, closing.

**Closed by jcesarmobile** 2020-06-26 14:53 UTC
