### ISSUE TITLE
getPicture randomly crashes

### ISSUE THREAD

**Issue by totiherms** [apache/cordova-plugin-camera#460] opened 2019-05-24 15:53 UTC
# Bug Report

## Problem
The app randomly crashes in ionic v3 when trying to take a picture. I've googled for this issue and tried various proposed solutions, with no success. Majority of them appeals to include correct information in AndroidManifest.xl, regarding to provider tag, but I think this part is ok:

<provider android:authorities="${applicationId}.provider" android:exported="false" android:grantUriPermissions="true" android:name="org.apache.cordova.camera.FileProvider">
            <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/camera_provider_paths" />
        </provider>

### What is expected to happen?
The camera takes a picture

### What does actually happen?
The app randomly crashes. Sometimes the picture is taken, sometimes the app crashes with the log

05-24 17:30:43.242 25976 25976 E AndroidRuntime: Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=34, result=-1, data=null} to activity {com.flsida.avhis/com.flsida.avhis.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
05-24 17:30:43.242 25976 25976 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4597)
05-24 17:30:43.242 25976 25976 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3990)
05-24 17:30:43.242 25976 25976 E AndroidRuntime: 	... 11 more
05-24 17:30:43.242 25976 25976 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
05-24 17:30:43.242 25976 25976 E AndroidRuntime: 	at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:591)
05-24 17:30:43.242 25976 25976 E AndroidRuntime: 	at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:565)
05-24 17:30:43.242 25976 25976 E AndroidRuntime: 	at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:403)
05-24 17:30:43.242 25976 25976 E AndroidRuntime: 	at org.apache.cordova.camera.CameraLauncher.onActivityResult(CameraLauncher.java:803)

### Command or Code
Accessing camera, simply using

`
const options: CameraOptions = {
        quality: 80,
        allowEdit:true,
        correctOrientation:true,
        destinationType: this.camera.DestinationType.FILE_URI,
        encodingType: this.camera.EncodingType.JPEG,
        mediaType: this.camera.MediaType.PICTURE,
        sourceType: this.camera.PictureSourceType.CAMERA
    }

this.camera.getPicture(options).then((fileUri) => {

        
    }, (err) => {
        console.log(err);
        
    });`

### Environment, Platform, Device
Ionic v3, Running on android devices 8 and 9

### Version information
Ionic:

   ionic (Ionic CLI)  : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.6
   @ionic/app-scripts : 3.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 8.0.0, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 1.2.1, (and 22 other plugins)

cordova-plugin-camera version 4.0.3

System:

   ios-deploy : 1.9.4
   NodeJS     : v10.15.1 (/usr/local/bin/node)
   npm        : 6.9.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.2.1 Build version 10E1001

## Checklist

- [ x] I searched for existing GitHub issues
- [ x] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above

**Comment by janpio** [comment] 2019-05-24 15:56
Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by totiherms** [comment] 2019-05-24 16:06
Hi, I've started a new ionic v3 app, and the issue is not reproduced... 

-I've matched all versions from package.json and plugins versions from the blanl project to my app
-I've checked the AndroidManifest.xml and the part of the cordova-plugin-camera it's exactly the same. 
-All the versions of package.json are the same
- I've removed the android platform and added it again

the problem in older app still persists

I'm trying to trace the error, I'd like to see the value of applicationId, but adding log.e on the plugin file seems have no effect when adb logcat, the lines are not printed

`      LOG.e(LOG_TAG, "Application id");
        LOG.e(LOG_TAG, applicationId);
       //crash here
       this.imageUri = new CordovaUri(FileProvider.getUriForFile(cordova.getActivity(),
                applicationId + ".provider",
                photo));`

**Comment by totiherms** [comment] 2019-05-27 13:22
Hi, I've tried with a fresh new ionic 4 app, 

 ionic start test4 blank

and the issue is present. The app randomly crashes on taking a picture from the camera

`05-27 15:19:46.911 13697 13697 E AndroidRuntime: FATAL EXCEPTION: main
05-27 15:19:46.911 13697 13697 E AndroidRuntime: Process: io.ionic.starter, PID: 13697
05-27 15:19:46.911 13697 13697 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=101, result=-1, data=Intent { dat=file:///storage/emulated/0/Android/data/io.ionic.starter/cache/1558963183223.jpg typ=image/jpeg }} to activity {io.ionic.starter/io.ionic.starter.MainActivity}: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
05-27 15:19:46.911 13697 13697 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4597)
05-27 15:19:46.911 13697 13697 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4639)
05-27 15:19:46.911 13697 13697 E AndroidRuntime: 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
05-27 15:19:46.911 13697 13697 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
05-27 15:19:46.911 13697 13697 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
05-27 15:19:46.911 13697 13697 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1977)
05-27 15:19:46.911 13697 13697 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-27 15:19:46.911 13697 13697 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
05-27 15:19:46.911 13697 13697 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6923)
05-27 15:19:46.911 13697 13697 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-27 15:19:46.911 13697 13697 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
05-27 15:19:46.911 13697 13697 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
05-27 15:19:46.911 13697 13697 E AndroidRuntime: Caused by: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
05-27 15:19:46.911 13697 13697 E AndroidRuntime: 	at org.apache.cordova.camera.CameraLauncher.getFileNameFromUri(CameraLauncher.java:1399)
05-27 15:19:46.911 13697 13697 E AndroidRuntime: 	at org.apache.cordova.camera.CameraLauncher.processResultFromCamera(CameraLauncher.java:548)
05-27 15:19:46.911 13697 13697 E AndroidRuntime: 	at org.apache.cordova.camera.CameraLauncher.onActivityResult(CameraLauncher.java:781)
05-27 15:19:46.911 13697 13697 E AndroidRuntime: 	at org.apache.cordova.CordovaInterfaceImpl.onActivityResult(CordovaInterfaceImpl.java:159)
05-27 15:19:46.911 13697 13697 E AndroidRuntime: 	at org.apache.cordova.CordovaActivity.onActivityResult(CordovaActivity.java:359)
05-27 15:19:46.911 13697 13697 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:7472)
05-27 15:19:46.911 13697 13697 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4590)`

is this a bug?

**Comment by janpio** [comment] 2019-05-27 13:43
Could be possible - but you should try with a plain _Cordova_ app. Currently the problem could be in the way Ionic and Ionic native actually use the plugin.

**Comment by totiherms** [comment] 2019-05-28 06:36
Hi again, I don't know if this issue it's exclusive of ionic or its cordova related, so sorry if this is not place to post. I did a trace of the vars, and sometimes, applicationId is null, that causes the crash on line 802 of CameraLauncher.java:

`
Uri tmpFile = FileProvider.getUriForFile(cordova.getActivity(),
                                applicationId + ".provider",
                                createCaptureFile(this.encodingType));
`

On a good execution, applicationId=com.flsida.avhis
and when crashes randomly: aplicationId=null

Why the value of applicationId is changed?

**Comment by indraraj26** [comment] 2019-05-28 13:01
Same issue i am facing,
https://github.com/ionic-team/ionic-native/issues/3040

**Comment by totiherms** [comment] 2019-05-28 14:02
I think is related to memory outage, and also the way cordova handles lifecycles. Here is a work around I'm implementing, works well in a simple page, but recreating a "more complex" page again (loading data from server, downloading images, getting data from firebase messaging ) seems a very bad solution, especially if what I want is to take a simple photo...

https://forum.ionicframework.com/t/solved-camera-plugin-restart-app-on-android/117828/8

and here a repository with the proposed solution

https://github.com/peterpeterparker/ionic-zurich-cordova-android-quirks

I've tried the media-capture plugin, same issue. I'll try camera preview plugin (https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview)

**Comment by gartorware** [comment] 2019-07-06 10:19
Do you have proguard active by any chance? 
I was having the same issue and it was solved after adding:
`-keep class com.abc.xyz.BuildConfig { *; }`
(where com.abc.xyz is my app package name) to my proguard rules file.

Found this solution [here](https://stackoverflow.com/questions/45938239/cordova-and-proguard-camera-plugin-npe-on-takepicture)

**Comment by pcsantana** [comment] 2019-09-18 18:50
[This](https://github.com/apache/cordova-plugin-camera/issues/486#issuecomment-518987216) resolved for me!
But why the plugin does not add this automatically I do not know.

**Comment by liuxiaoy** [comment] 2019-12-06 09:36
it is known as a bug of Cordova cli.[apache/cordova-common#89](https://github.com/apache/cordova-common/pull/89)

**Comment by timbru31** [comment] 2020-04-02 17:39
Closing due to lack of a working MRE and some proposed alternatives/solutions.

**Closed by timbru31** 2020-04-02 17:39 UTC
Labels: bug, platform: android
