### ISSUE TITLE
Camera fails while I build final release.

### ISSUE THREAD

**Issue by kennedyngigi4** [apache/cordova-plugin-camera#743] opened 2021-07-01 13:55 UTC
Camera fails in my final app release of ionic 5 while using ( ionic cordova build android --prod --release )

But it was working fine in an apk generated through ( ionic cordova build android )

Any help on this issue?

**Comment by timbru31** [comment] 2021-07-01 15:55
Duplicate of #742

**Closed by timbru31** 2021-07-01 15:55 UTC
