### ISSUE TITLE
App crash after allowing the camera permission

### ISSUE THREAD

**Issue by Mohammad-Toufiq-Pathan** [apache/cordova-plugin-camera#744] opened 2021-07-04 18:05 UTC
Hi all, I am using Android 11  camera plugin 5.0.2, when I click on camera icon permission dialog will appear when I allow the permission app getting crash, this is happening only in release build, in debug build it's working fine, please help me out

**Comment by dantheman2865** [comment] 2021-08-10 12:35
I am also experiencing the same problem on 5.0.3. Here are the exception logs from my Android App:

```
2021-08-10 08:31:27.551 4303-4598/my.app.name V/Capacitor/Plugin: To native (Cordova plugin): callbackId: Camera770925669, service: Camera, action: takePicture, actionArgs: [100,0,1,-1,-1,0,0,false,false,false,null,0]
2021-08-10 08:31:27.563 4303-4598/my.app.name W/System.err: java.lang.ClassNotFoundException: my.app.name.BuildConfig
2021-08-10 08:31:27.657 4303-4598/my.app.name W/System.err:     at java.lang.Class.classForName(Native Method)
2021-08-10 08:31:27.657 4303-4598/my.app.name W/System.err:     at java.lang.Class.forName(Class.java:454)
2021-08-10 08:31:27.657 4303-4598/my.app.name W/System.err:     at java.lang.Class.forName(Class.java:379)
2021-08-10 08:31:27.658 4303-4598/my.app.name W/System.err:     at org.apache.cordova.BuildHelper.getBuildConfigValue(BuildHelper.java:54)
2021-08-10 08:31:27.659 4303-4598/my.app.name W/System.err:     at org.apache.cordova.camera.CameraLauncher.execute(CameraLauncher.java:149)
2021-08-10 08:31:27.659 4303-4598/my.app.name W/System.err:     at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
2021-08-10 08:31:27.660 4303-4598/my.app.name W/System.err:     at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
2021-08-10 08:31:27.660 4303-4598/my.app.name W/System.err:     at com.getcapacitor.MessageHandler.callCordovaPluginMethod(MessageHandler.java:123)
2021-08-10 08:31:27.661 4303-4598/my.app.name W/System.err:     at com.getcapacitor.MessageHandler.postMessage(MessageHandler.java:61)
2021-08-10 08:31:27.661 4303-4598/my.app.name W/System.err:     at android.os.MessageQueue.nativePollOnce(Native Method)
2021-08-10 08:31:27.662 4303-4598/my.app.name W/System.err:     at android.os.MessageQueue.next(MessageQueue.java:342)
2021-08-10 08:31:27.662 4303-4598/my.app.name W/System.err:     at android.os.Looper.loop(Looper.java:197)
2021-08-10 08:31:27.663 4303-4598/my.app.name W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:67)
2021-08-10 08:31:27.668 4303-4598/my.app.name W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "my.app.name.BuildConfig" on path: DexPathList[[zip file "/data/app/~~piXwCSu6z0GFSDKzF5J3MQ==/my.app.name-l6Kcd9m8pwVqzEmG13Ny-w==/base.apk"],nativeLibraryDirectories=[/data/app/~~piXwCSu6z0GFSDKzF5J3MQ==/my.app.name-l6Kcd9m8pwVqzEmG13Ny-w==/lib/arm64, /system/lib64, /system/system_ext/lib64, /product/lib64]]
2021-08-10 08:31:27.669 4303-4598/my.app.name W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
2021-08-10 08:31:27.669 4303-4598/my.app.name W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
2021-08-10 08:31:27.670 4303-4598/my.app.name W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
2021-08-10 08:31:27.670 4303-4598/my.app.name W/System.err: 	... 13 more
2021-08-10 08:31:27.699 4303-4303/my.app.name D/Capacitor: App paused
2021-08-10 08:31:29.968 4303-4303/my.app.name D/Capacitor: Unable to find a Capacitor plugin to handle permission requestCode, trying Cordova plugins 2
2021-08-10 08:31:30.096 4303-4303/my.app.name D/AndroidRuntime: Shutting down VM
2021-08-10 08:31:30.108 4303-4303/my.app.name E/AndroidRuntime: FATAL EXCEPTION: main
    Process: my.app.name, PID: 4303
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=2, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {my.app.name/io.ionic.starter.MainActivity}: java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority null.cordova.plugin.camera.provider
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5091)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5132)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2126)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:250)
        at android.app.ActivityThread.main(ActivityThread.java:7766)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
     Caused by: java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority null.cordova.plugin.camera.provider
        at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:606)
        at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:579)
        at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:417)
        at org.apache.cordova.camera.CameraLauncher.takePicture(CameraLauncher.java:297)
        at org.apache.cordova.camera.CameraLauncher.onRequestPermissionResult(CameraLauncher.java:1319)
        at com.getcapacitor.cordova.MockCordovaInterfaceImpl.handlePermissionResult(MockCordovaInterfaceImpl.java:32)
        at com.getcapacitor.Bridge.onRequestPermissionsResult(Bridge.java:847)
        at com.getcapacitor.BridgeActivity.onRequestPermissionsResult(BridgeActivity.java:188)
        at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8570)
        at android.app.Activity.dispatchActivityResult(Activity.java:8418)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5084)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5132) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2126) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:250) 
        at android.app.ActivityThread.main(ActivityThread.java:7766) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958) 
```

**Comment by dantheman2865** [comment] 2021-08-23 01:41
I solved this by changing the package name in the AndroidManifest.xml file. It was still set to the default.

**Comment by martinbertinat** [comment] 2021-09-08 12:04
Hi @toufiqpathan did you find a solution? I'm having a similar problem with Camera plugin and Android 11, "no image selected". Thanks

**Comment by Mohammad-Toufiq-Pathan** [comment] 2021-09-09 07:31
Hi @martinbertinat didn't find any solution

**Comment by thierry1129** [comment] 2021-09-24 01:19
i encountered the identical problem as @Mohammad-Toufiq-Pathan  and @toufiqpathan . I'm using 6.0.0 for camera plugin and 10.1.1 for cordova-android. 

camera works for debug builds, but when i switch the build type from debug to release in android studio, the app crashes showing the exact same log as @toufiqpathan . 

any suggestions on a temporary workaround? @erisu @breautek

**Comment by thierry1129** [comment] 2021-09-24 01:27
Sorry I know very little about Android development. I have a hunch that this might be caused by cordova-android. 
when I used cordova-android 9 along with camera 5.0.1,  camera works fine for release builds on android api level 28. 
but cordova-android 10.1.1 along with camera 5.0.1 causes the crash mentioned above on android api 28.

**Comment by thierry1129** [comment] 2021-09-24 01:31
@martinbertinat @Mohammad-Toufiq-Pathan @toufiqpathan guys which cordova-android version are you guys using

**Comment by Mohammad-Toufiq-Pathan** [comment] 2021-09-24 01:38
@thierry1129  I am using android 10.1.1

**Comment by biswas-houm** [comment] 2021-11-08 12:34
How can we rely on this  fix? we need something from the plugin author itself

**Comment by sandeepwip** [comment] 2022-03-09 14:19
@Jeffrey-Lang I tried your solution but same issue still facing the problem.Any suggession please.
Sandeep

**Comment by Jeffrey-Lang** [comment] 2022-03-09 14:35
@sandeepwip have you tried the fix that worked for @[dantheman2865](https://github.com/dantheman2865)

What i know from working with this is that is all about which versions of plugins you use.
So you might want to try to disable some plugins you have and check if it works then then one by one enable them to see which one it causes.

It can also be your ionic / angular version

**Comment by ashilanazeer1** [comment] 2022-06-25 08:26
> i encountered the identical problem as @Mohammad-Toufiq-Pathan and @toufiqpathan . I'm using 6.0.0 for camera plugin and 10.1.1 for cordova-android.
> 
> camera works for debug builds, but when i switch the build type from debug to release in android studio, the app crashes showing the exact same log as @toufiqpathan .
> 
> any suggestions on a temporary workaround? @erisu @breautek



> @thierry1129 I already fixed it.
> 
> in the file src/android/CameraLauncher.java
> 
> Change: `this.applicationId = (String) BuildHelper.getBuildConfigValue(cordova.getActivity(), "APPLICATION_ID");` To: `this.applicationId = cordova.getContext().getPackageName();`
> 
> That did the trick for me. Hope it will help someone else!
in this method we have to replace this line of code after downloading the plugin when we do the build right?. Is there any version of camera-plugin that works with ionic 3 without crashing camera

**Comment by ashilanazeer1** [comment] 2022-06-25 08:28
@Jeffrey-Lang 
In this method we have to replace this line of code after downloading the plugin when we do the build right?. Is there any version of camera-plugin that works with ionic 3 without crashing camera

**Comment by nadeeth** [comment] 2022-10-20 04:25
I had the same issue in production builds. Fixed by adding this inside the "<platform name='android'>" section of the plugin xml. It will add this provider meta-data to AndroidManifest.xml in the build time. 

`<config-file parent="/manifest/application" target="AndroidManifest.xml" xmlns:android="http://schemas.android.com/apk/res/android">
            <provider android:authorities="${applicationId}.fileOpener2.provider" android:exported="false" android:grantUriPermissions="true" android:name="io.github.pwlin.cordova.plugins.fileopener2.FileProvider">
                <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/opener_paths" />
            </provider>
            <provider android:authorities="${applicationId}.cordova.plugin.camera.provider" android:exported="false" android:grantUriPermissions="true" android:name="org.apache.cordova.camera.FileProvider">
                <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/camera_provider_paths" />
            </provider>
        </config-file>`

**Comment by breautek** [comment] 2023-09-06 12:01
Should be fixed by https://github.com/apache/cordova-plugin-camera/pull/827

**Closed by breautek** 2023-09-06 12:01 UTC
