### ISSUE TITLE
4.1.0 release

### ISSUE THREAD

**Issue by kaiukdevelopment** [apache/cordova-plugin-camera#415] opened 2019-01-24 12:11 UTC
Will 4.1.0 be released soon? There is a fix for the browser platform which I'd like but it's not been released yet. (CB-9852)

**Comment by kamiljackiewicz** [comment] 2019-02-06 15:38
Please release new build. Waiting for bubfix:
https://github.com/apache/cordova-plugin-camera/commit/5c23b65af9b11fa3a17bd44513418113dea9b8ed

**Comment by WIStudent** [comment] 2019-02-18 10:48
I am also waiting for a new release because of 5c23b65.

As a workaround I am currently installing the plugin with
`cordova plugin add https://github.com/apache/cordova-plugin-camera.git`

You can also use 
`cordova plugin add https://github.com/apache/cordova-plugin-camera.git#COMIIT_ID`
if you want a specific commit.

**Comment by BorntraegerMarc** [comment] 2019-03-12 20:18
I also would love to see a new version since I need the fix for https://github.com/apache/cordova-plugin-camera/issues/329 🙂 can I help in anyway to get the new release out?

@WIStudent yeah you can specify a commit hash but I don't feel so comfortable with using a not-approved-by-apache version of this plugin 🙂

**Comment by BorntraegerMarc** [comment] 2019-04-25 17:49
Okay, seriously the last release was now over a year ago 😄 It nearly seems like this plugin is not really supported anymore by the apache team...

**Comment by janpio** [comment] 2019-04-25 18:09
The Apache Cordova team does what it can, and in the last few months the very limited time and resources was focused on CLI and platforms. 

Currently we are working on the CI setup for the plugins and rolling that out to the first plugins. 

When that is done, and we know what is broken and what is not, we can decide if the current states of the repositories can be released as they are - or if further work is necessary.

So this plugin is still supported, and it will be released as soon as possible.

**Closed by janpio** 2019-04-25 18:09 UTC

**Comment by BorntraegerMarc** [comment] 2019-04-25 18:16
@janpio Thanks for the update. I didn't want to seem rude. I was just curious for an official statement from the maintainers and wether one can help you guys out.

**Comment by janpio** [comment] 2019-04-25 20:18
No worries, I completely understand why these questions are posted - it is frustrating for the maintainers as well that we can't just hit a "Release" button and everything be fine.

You can test the current `master` version of the plugin and see if everything works as intended, with a focus on the code that was added after the last release. In this case, this would be the list to look at: https://github.com/apache/cordova-plugin-camera/compare/4.0.3...master
