### ISSUE TITLE
Android Q support , Migrating legacystorage

### ISSUE THREAD

**Issue by deepti1408** [apache/cordova-plugin-camera#675] opened 2020-10-11 13:50 UTC
The plugin uses FileProvider.getUriForFile() whichis now nolonger supported fromAndroid Q scoped storage. Please release an update with new storage scope Mediastore api for android Q support

**Comment by jcesarmobile** [comment] 2020-10-14 23:52
Can you provide more information about it? 
The docs don’t mention anything about not being supported nor being deprecated on android Q
https://developer.android.com/reference/androidx/core/content/FileProvider#getUriForFile(android.content.Context,%20java.lang.String,%20java.io.File)

**Comment by deepti1408** [comment] 2020-10-15 04:43
hi @jcesarmobile , from android Q, getExternalStorageDirectory is deprecated. In the code, fileProvider is using this path for saving captured images. This is part of scoped storage introduced in android 10. Please refer links:
[https://developer.android.com/training/data-storage/use-cases#migrate-legacy-storage](https://developer.android.com/training/data-storage/use-cases#migrate-legacy-storage)
[https://commonsware.com/blog/2019/06/07/death-external-storage-end-saga.html](https://commonsware.com/blog/2019/06/07/death-external-storage-end-saga.html)

**Comment by jcesarmobile** [comment] 2020-10-15 07:34
That’s totally different from what you said

**Comment by jcesarmobile** [comment] 2020-10-15 07:37
Duplicate of https://github.com/apache/cordova-plugin-camera/issues/534

**Closed by jcesarmobile** 2020-10-15 07:37 UTC
