### ISSUE TITLE
Cannot open camera on pixel 6 with sdk30

### ISSUE THREAD

**Issue by aymen110** [apache/cordova-plugin-camera#809] opened 2022-09-26 08:34 UTC
# Bug Report
Cannot open camera on pixel 6 with sdk30

## Problem
The problem that is i'm not able to open the camera on some phones like (pixel 6), but on other 
mobile phone i don't have the problem. So i think the problem is that i'm on sdk30 and pixel 6 or pixel 2.

I tried to get the new version of the camera plugin (6.0.0) which i think the problem was resolved with the modifications on the 
file config.xml like in #684, but this did not resolve my problem.

I found another solution to the problem wich was this one #739, i made the modification in local on my project and i was able to open the camera on the pixel 6 and pixel 2.
But this solution is not merged on any branch, i don't know why :/

So i need your help to resolve my problem with openning the camera on sdk30 with pixel 6.

Or if you have an alternative for the cordova-plugin-camera this could maybe help me.

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment] 2022-09-26 10:26
Possible duplicate of https://github.com/apache/cordova-plugin-camera/issues/763

**Comment by aymen110** [comment] 2022-09-26 14:51
The solution mentioned in the #763 does not work for me.

**Comment by jcesarmobile** [comment] 2023-03-06 23:06
can you provide a sample app?

**Comment by jcesarmobile** [comment] 2023-04-26 00:00
closing since there was no response

**Closed by jcesarmobile** 2023-04-26 00:00 UTC
Labels: info-needed
