### ISSUE TITLE
Where to initialize `navigator.camera`

### ISSUE THREAD

**Issue by JacobHornbeck** [apache/cordova-plugin-camera#824] opened 2023-01-21 21:52 UTC
In the README it says that the plugin creates a global `navigator.camera` object, but it doesn't seem to be doing that for me. I looked up why, and there was something that was saying to initialize it, but I don't see how or where to do that. Can someone please help?

**Comment by breautek** [comment] 2023-01-21 23:11
Plugin APIs may not be initialized immediately, but happens as a part of loading the `cordova.js` file.

You must wait for the `deviceready` event, which will be fired when all plugins are ready.

```javascript
document.addEventListener("deviceready", () => {
    //navigator.camera can be safely used
});
```

Closing as not a bug.

**Closed by breautek** 2023-01-21 23:11 UTC
