### ISSUE TITLE
Crash after taking a picture from gallery

### ISSUE THREAD

**Issue by manel00** [apache/cordova-plugin-camera#473] opened 2019-07-02 15:25 UTC
# Bug Report
Crash after taking a picture from gallery, 4,42 mbps - 4032x4032px JPG on Android Xiaomi Mi 8 Lite (Last Android version)
### What is expected to happen?
It shouldn't crash

### What does actually happen?
Crash and cannot take the error, maybe is the size

## Information

  goPhotoGallery() {
    const options: CameraOptions = {
      quality: 50,
      destinationType: this.camera.DestinationType.DATA_URL,
      encodingType: this.camera.EncodingType.JPEG,
      mediaType: this.camera.MediaType.PICTURE,
      sourceType: this.camera.PictureSourceType.PHOTOLIBRARY,
      correctOrientation: true,
    }

    this.camera.getPicture(options).then(imageData => {
      let base64Image = `data:image/jpeg;base64,${imageData}`;
      this.images = base64Image;
    }).catch(err => {
      this.service.presentToast(err, 'danger');
    });
  }

## Checklist

- [X ] I searched for existing GitHub issues
- [ X] I updated all Cordova tooling to most recent version
- [ X] I included all the necessary information above

**Comment by janpio** [comment] 2019-07-02 15:38
Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by LucasMenchi** [comment] 2019-07-03 13:33
The problem is with your destination type in the config, the image is big and is consuming a lot of memory. Change the destination to FILE_URI o NATIVE_URI, quote to the docs:

> NOTE: Photo resolution on newer devices is quite good. Photos selected from the device's gallery are not downscaled to a lower quality, even if a quality parameter is specified. To avoid common memory problems, set Camera.destinationType to FILE_URI rather than DATA_URL.

**Comment by fokunn** [comment] 2019-07-05 17:34
I confirm it crashes with with Camera.destinationType set  to FILE_URI, and with HUAWEI DUB-AL00, android version: 8.1.0, ENUI version 8.2.0  as well.

logcat output: 
```
--------- beginning of crash
07-05 23:51:40.477 17852 17920 E AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
07-05 23:51:40.477 17852 17920 E AndroidRuntime: Process: ccc.xxxxxx.xxxxxxxx, PID: 17852
07-05 23:51:40.477 17852 17920 E AndroidRuntime: java.lang.NumberFormatException: For input string: "raw:/storage/emulated/0/Download/share_image_1562173902011.png"
07-05 23:51:40.477 17852 17920 E AndroidRuntime: 	at java.lang.Long.parseLong(Long.java:590)
07-05 23:51:40.477 17852 17920 E AndroidRuntime: 	at java.lang.Long.valueOf(Long.java:804)
07-05 23:51:40.477 17852 17920 E AndroidRuntime: 	at org.apache.cordova.camera.FileHelper.getRealPathFromURI_API11_And_Above(FileHelper.java:101)
07-05 23:51:40.477 17852 17920 E AndroidRuntime: 	at org.apache.cordova.camera.FileHelper.getRealPath(FileHelper.java:60)
07-05 23:51:40.477 17852 17920 E AndroidRuntime: 	at org.apache.cordova.camera.CameraLauncher.processResultFromGallery(CameraLauncher.java:682)
07-05 23:51:40.477 17852 17920 E AndroidRuntime: 	at org.apache.cordova.camera.CameraLauncher.access$000(CameraLauncher.java:74)
07-05 23:51:40.477 17852 17920 E AndroidRuntime: 	at org.apache.cordova.camera.CameraLauncher$1.run(CameraLauncher.java:830)
07-05 23:51:40.477 17852 17920 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
07-05 23:51:40.477 17852 17920 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
07-05 23:51:40.477 17852 17920 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:784)

```

**Comment by dpolivy** [comment] 2019-07-08 23:45
FWIW, I'm seeing the same exception stack in the wild with my app. User is on a OnePlus 6 device, and choosing a file from the gallery. I am using `Camera.DestinationType.FILE_URI`.

I don't yet have a specific repro case for this, but if you're able to share the image you use to reproduce the crash, I can take a look at coming up with a more robust fix.

**Comment by dpolivy** [comment] 2019-07-09 00:22
What version of the plugin are you using? Can you try the latest? It looks like this was fixed in 4.1.0 via this commit:

https://github.com/apache/cordova-plugin-camera/commit/5c23b65af9b11fa3a17bd44513418113dea9b8ed

**Comment by fokunn** [comment] 2019-07-11 08:13
> What version of the plugin are you using? Can you try the latest? It looks like this was fixed via this commit:
> 
> [5c23b65](https://github.com/apache/cordova-plugin-camera/commit/5c23b65af9b11fa3a17bd44513418113dea9b8ed)


If I am not wrong, I installed it through  npm, not github.   strange...  anyway this should be closed then.

**Comment by manel00** [comment] 2019-07-11 08:26
I'm sorry i'm  a newbie at this subject, what code should i execute to update it? thank you so much

**Comment by dpolivy** [comment] 2019-07-11 18:16
Try this:

`````
cordova plugin rm cordova-plugin-camera
cordova plugin install https://github.com/apache/cordova-plugin-camera

**Comment by manel00** [comment] 2019-07-14 15:07
the last command didn't do anything, are you sure?

**Comment by dpolivy** [comment] 2019-07-14 22:34
Sorry, it's `add` instead of `install`:

`cordova plugin add https://github.com/apache/cordova-plugin-camera`

**Comment by fokunn** [comment] 2019-07-15 05:32
better add from git hub.

**Comment by PieterVanPoyer** [comment] 2021-05-19 20:46
@manel00 is this issue still present with the latest plugin version?

**Comment by PieterVanPoyer** [comment] 2021-06-05 19:03
Closing ticket due to lack of response. Issue is probably solved with latest Cordova tooling.

**Closed by PieterVanPoyer** 2021-06-05 19:03 UTC
Labels: info-needed, platform: android
