### ISSUE TITLE
[AndroidX] Task :app:mergeDebugJavaResource FAILED when add plugin cordova-plugin-camera

### ISSUE THREAD

**Issue by theparitt** [apache/cordova-plugin-camera#697] opened 2020-12-16 09:09 UTC
# Bug Report

### What is expected to happen?
I cannot run cordova 

### What does actually happen?
Task :app:mergeDebugJavaResource FAILED
I tried to enable adnroidx but the error is still 

## Information
> Task :app:compileDebugJavaWithJavac FAILED
C:\Users\I-w-I\Dropbox\mobile\mormit\platforms\android\app\src\main\java\org\apache\cordova\camera\CameraLauncher.java:42: error: package android.support.v4.content does not exist
import android.support.v4.content.FileProvider;
                                 ^
C:\Users\I-w-I\Dropbox\mobile\mormit\platforms\android\app\src\main\java\org\apache\cordova\camera\FileProvider.java:21: error: package android.support.v4.content does not exist
public class FileProvider extends android.support.v4.content.FileProvider {}
                                                            ^
C:\Users\I-w-I\Dropbox\mobile\mormit\platforms\android\app\src\main\java\org\apache\cordova\camera\CameraLauncher.java:296: error: cannot find symbol
        this.imageUri = FileProvider.getUriForFile(cordova.getActivity(),
                                    ^
  symbol:   method getUriForFile(Activity,String,File)
  location: class FileProvider
C:\Users\I-w-I\Dropbox\mobile\mormit\platforms\android\app\src\main\java\org\apache\cordova\camera\CameraLauncher.java:823: error: cannot find symbol
                        Uri tmpFile = FileProvider.getUriForFile(cordova.getActivity(),
                                                  ^
  symbol:   method getUriForFile(Activity,String,File)
  location: class FileProvider
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\I-w-I\Dropbox\mobile\mormit\platforms\android\app\src\main\java\org\apache\cordova\file\AssetFilesystem.java uses unchecked or unsafe operations.    
Note: Recompile with -Xlint:unchecked for details.
4 errors

> Task :app:mergeDebugJavaResource FAILED

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > com.google.common.base.VerifyException (no error message)

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment] 2020-12-16 12:57
This plugin does not support androidx because it's using the old android support libraries.

You may have luck by installing the [cordova-plugin-androidx-adapter](https://www.npmjs.com/package/cordova-plugin-androidx-adapter) which does it's best to "upgrade" plugins that is using the old support libraries into the equivalent androidx libraries.

**Comment by jcesarmobile** [comment] 2020-12-16 15:16
closing as duplicate of https://github.com/apache/cordova-plugin-camera/issues/405

**Closed by jcesarmobile** 2020-12-16 15:16 UTC
Labels: AndroidX

**Comment by theparitt** [comment] 2020-12-17 12:24
I don't mind to hse the old library since all other codes are based on the old Android library too. 

I think some parts of cordova-camera-plugin uses the android x, doesn't it?  because when I compile the code, the compile r says like cannot find "android.support.v4.content.FileProvider"

How could I fix this problem. I am now using Cordova 9.. Windows 10 64-bit.

**Comment by jcesarmobile** [comment] 2020-12-17 15:09
If `cordova-plugin-androidx-adapter` didn't work, try using [jetifier](https://www.npmjs.com/package/jetifier).

The problem is you can't use non AndroidX libraries with AndroidX libraries, as long as one of your plugins uses AndroidX, you'll need to update/patch all.

cordova-plugin-camera doesn't use AndroidX yet.

**Comment by breautek** [comment] 2020-12-17 15:12
@theparitt  I may have incorrectly assume that you have AndroidX enabled. Can you confirm that you do? The mentioned errors is usually a side effect of having AndroidX enabled and trying to use plugins that uses the old support libraries, hence my assumption.

**Comment by nghongphuong94** [comment] 2021-06-17 07:44
> This plugin does not support androidx because it's using the old android support libraries.
> 
> You may have luck by installing the [cordova-plugin-androidx-adapter](https://www.npmjs.com/package/cordova-plugin-androidx-adapter) which does it's best to "upgrade" plugins that is using the old support libraries into the equivalent androidx libraries.
> 
> I'll keep this issue open -- I think our next cordova-android major may drop support for the old support libraries. But I don't think that decision has been fully concluded yet.

Thanks @breautek, I faced the same issue and installed cordova-plugin-androidx-adapter then it worked!

**Comment by Civile** [comment] 2021-09-14 15:35
> This plugin does not support androidx because it's using the old android support libraries.
> 
> You may have luck by installing the [cordova-plugin-androidx-adapter](https://www.npmjs.com/package/cordova-plugin-androidx-adapter) which does it's best to "upgrade" plugins that is using the old support libraries into the equivalent androidx libraries.
> 
> I'll keep this issue open -- I think our next cordova-android major may drop support for the old support libraries. But I don't think that decision has been fully concluded yet.

Excellent solution, it works
