### ISSUE TITLE
 If you do not allow access to the camera, it will be in English

### ISSUE THREAD

**Issue by megumih** [apache/cordova-plugin-camera#483] opened 2019-08-02 02:58 UTC
# Bug Report
I use this plugin.
I want to take picture.so,
When I select Don't allow in modal permission,and this message 
「"Access to the camera has been prohibited; please enable it in the Settings app to continue.」.

This message is English, but I want to change Japanese.
Plese teach me how to chage Language.

## Information

this plugin source
cordova-plugin-camera/src/ios/CDVCamera.m

// Denied; show an alert
                     dispatch_async(dispatch_get_main_queue(), ^{
                         UIAlertController *alertController = [UIAlertController alertControllerWithTitle:[[NSBundle mainBundle] objectForInfoDictionaryKey:@"CFBundleDisplayName"] message:NSLocalizedString(@"Access to the camera has been prohibited; please enable it in the Settings app to continue.", nil) preferredStyle:UIAlertControllerStyleAlert];
                         [alertController addAction:[UIAlertAction actionWithTitle:NSLocalizedString(@"OK", nil) style:UIAlertActionStyleDefault handler:^(UIAlertAction * _Nonnull action) {
                             [weakSelf sendNoPermissionResult:command.callbackId];
                         }]];

![IMG_60AFF44E3565-1](https://user-images.githubusercontent.com/10084100/62341037-b3194400-b51c-11e9-9a0b-4a2f68418ed7.jpeg)

**Comment by timbru31** [comment] 2019-08-03 14:58
Dupe of #392

**Closed by timbru31** 2019-08-03 14:58 UTC

**Comment by megumih** [comment] 2019-08-03 15:37
I want to try this method
please teach me　in detail

**Comment by timbru31** [comment] 2019-08-04 09:20
https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPInternational/LocalizingYourApp/LocalizingYourApp.html

**Comment by megumih** [comment] 2019-08-08 07:16
@timbru31 thanks. 
I try this Method,but don't work.
After,My project build.
Look at the attached capture.


Not included in directory ''Localizable.strings''.
Why?
I'm using .xcworkspace file.


<img width="995" alt="スクリーンショット 2019-08-08 16 08 59" src="https://user-images.githubusercontent.com/10084100/62682694-be2a1380-b9f7-11e9-95a7-ce5e7f1164dd.png">

<img width="231" alt="スクリーンショット 2019-08-08 16 14 31" src="https://user-images.githubusercontent.com/10084100/62682685-b9655f80-b9f7-11e9-85f6-6e3fd0c76bb1.png">

**Comment by hendrik244** [comment] 2020-09-17 16:24
Hi,

I'm currently facing the same error.
When I create the Localization files for the pods and importing the .strings file, the next time, when I run pods install they are removed again.

What's the solution for that?
Do I have to import them somewhere that the pod consider them?

Help would be nice.
