### ISSUE TITLE
Android : THREAD WARNING: exec() call to Camera.takePicture blocked the main thread for 24ms. Plugin should use CordovaInterface.getThreadPool

### ISSUE THREAD

**Issue by Petrik-a-dost** [apache/cordova-plugin-camera#528] opened 2019-11-20 16:41 UTC
# Bug Report
W/PluginManager: THREAD WARNING: exec() call to Camera.takePicture blocked the main thread for 24ms. Plugin should use CordovaInterface.getThreadPool().

## Problem
If I choose picture from photolibrary or make a photo do it nothing and picture is not transform to imageData.

### What is expected to happen?
I expected that I get picture in imageData.

### What does actually happen?
It happend nothing

## Information
D/SystemWebChromeClient: file:///android_asset/www/js/requestDetailController.js: Line 1402 : jede1
I/chromium: [INFO:CONSOLE(1402)] "jede1", source: file:///android_asset/www/js/requestDetailController.js (1402)
I/zygote: Do partial code cache collection, code=117KB, data=99KB
I/zygote: After code cache collection, code=117KB, data=99KB
I/zygote: Increasing code cache capacity to 512KB
D/CordovaActivity: Paused the activity.
W/PluginManager: THREAD WARNING: exec() call to Camera.takePicture blocked the main thread for 24ms. Plugin should use CordovaInterface.getThreadPool().
D/ViewRootImpl@2ea370f[MainActivity]: ViewPostIme pointer 1
D/InputMethodManager: HSIFW - flag : 0 Pid : 9928
D/ViewRootImpl@2ea370f[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 0
D/OpenGLRenderer: eglDestroySurface = 0xce1afa80
D/ViewRootImpl@2ea370f[MainActivity]: Relayout returned: old=[0,0][720,1280] new=[0,0][720,1280] result=0x5 surface={valid=false 0} changed=true
D/ViewRootImpl@2ea370f[MainActivity]: Relayout returned: old=[0,0][720,1280] new=[0,0][720,1280] result=0x1 surface={valid=false 0} changed=false
D/InputTransport: Input channel destroyed: fd=114
D/CordovaActivity: Stopped the activity.
D/ViewRootImpl@2ea370f[MainActivity]: Relayout returned: old=[0,0][720,1280] new=[0,0][720,1280] result=0x1 surface={valid=false 0} changed=false
D/CordovaActivity: Incoming Result. Request code = 49
D/CordovaInterfaceImpl: Sending activity result to plugin
D/CordovaActivity: Started the activity.
D/CordovaActivity: Resumed the activity.
V/Surface: sf_framedrop debug : 0x4f4c, game : false, logging : 0
D/ViewRootImpl@2ea370f[MainActivity]: Relayout returned: old=[0,0][720,1280] new=[0,0][720,1280] result=0x7 surface={valid=true 3459241984} changed=true
D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [720x1280]-format:1
D/OpenGLRenderer: eglCreateWindowSurface = 0xce1afa60
D/CameraLauncher: File location is: /storage/emulated/0/Pictures/IMG_20191120_170913.jpg
D/ViewRootImpl@2ea370f[MainActivity]: MSG_RESIZED_REPORT: frame=Rect(0, 0 - 720, 1280) ci=Rect(0, 0 - 0, 0) vi=Rect(0, 48 - 0, 0) or=1
D/ViewRootImpl@2ea370f[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 1
V/InputMethodManager: Starting input: tba=android.view.inputmethod.EditorInfo@ece817c nm : com.bosch.testinglaboratoryapp ic=null
I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport: Input channel constructed: fd=118
D/ViewRootImpl@2ea370f[MainActivity]: MSG_RESIZED: frame=Rect(0, 0 - 720, 1280) ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
W/ExifInterface: Skip the tag entry since tag number is not defined: 2
W/ExifInterface: Skip the tag entry since tag number is not defined: 2
I/zygote: Starting a blocking GC NativeAlloc
W/CordovaPlugin: Attempted to send a second callback for ID: Camera1516453671
                 Result was:"\/9j\/4AAQSkZJRgABAQAAAQABAAD\/2wBDAP\/\/\/\/\  etc..... etc...."

### Command or Code

var options = {
      quality: 80,
      destinationType: Camera.DestinationType.DATA_URL,
      sourceType: Camera.PictureSourceType.SAVEDPHOTOALBUM,
      allowEdit: false,
      encodingType: Camera.EncodingType.JPEG,
      popoverOptions: CameraPopoverOptions,
      saveToPhotoAlbum: false,
      correctOrientation:true,
      mediaType: Camera.MediaType.PICTURE,
    };
      console.log("jede1");
    $cordovaCamera.getPicture(options).then(function(imageData) {
      console.log("jede");
      alert(imageData);
      // in right case program continue to this thread but it nothing happens
    }, function(err) {
      // error
      alert(err);
    });
    $cordovaCamera.cleanup().then();

### Environment, Platform, Device
Android Studio, Android, Samsung Galaxy J3(2017)

### Version information
Android Studion, cordova-plugin-camera: 4.1.0, cordova-android: 8.1.0, @ionic/lab: 1.0.18, @ionic/v1-toolkit: 2.0.1, 

## Checklist

- [ ] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment] 2019-11-20 16:50
> W/PluginManager: THREAD WARNING: exec() call to Camera.takePicture blocked the main thread for 24ms. Plugin should use CordovaInterface.getThreadPool().

This is just a warning stating that the main thread was blocked for 24ms (which meant UI frames were to be dropped). This has no relation to your reported behaviour, especially since it was only blocked for 24ms.

> Result was:"/9j/4AAQSkZJRgABAQAAAQABAAD/2w

This suggests that the data is actually being sent to the JS.

Note that when using the `DATA_URL` this could take a  long time (and consumes a lot of memory) because the binary data is represented in a base64 encoded string, which will be approximately 40% larger than the actual binary data.

Modern phones today captures these images in a very large resolution. See the note in the [docs](https://github.com/apache/cordova-plugin-camera#cameragetpicturesuccesscallback-errorcallback-options)...

>NOTE: Photo resolution on newer devices is quite good. Photos selected from the device's gallery are not downscaled to a lower quality, even if a quality parameter is specified. To avoid common memory problems, set Camera.destinationType to FILE_URI rather than DATA_URL.

On modern phones it is a better approach to use a FILE_URI destination instead, then read the file into a blob, which has the capability of creating blob urls without having a base64 encoded image in the javascript memory. Blob urls can be used similar to data urls, such as inside the src attribute of an img tag.

This keeps handling of the binary data outside of the javascript environment, freeing up its only thread and keep the javascript memory space low.

This is likely related or duplicate of https://github.com/apache/cordova-plugin-camera/issues/499

**Comment by PieterVanPoyer** [comment] 2021-05-29 21:01
@Petrik-a-dost  is this issue still present with the latest version (5.0.2). If not, please close this issue. If it is present, please provide a reproduction case.

**Comment by PieterVanPoyer** [comment] 2021-06-02 21:14
Closed without fixing because there is no reproduction case provided and it's probably a duplicate of #499

**Closed by PieterVanPoyer** 2021-06-02 21:14 UTC
Labels: info-needed, platform: android
