### ISSUE TITLE
Support for cordova-plugin-camera 7.0 on Capacitor

### ISSUE THREAD

**Issue by rbenedettix** [apache/cordova-plugin-camera#856] opened 2023-09-21 14:20 UTC
I tried implementing cordova-plugin-camera 7.0 in my Capacitor 5 project directly but it gives me an error like this:
Error: Module not found: Error: Can't resolve 'cordova-plugin-camera'

My import is:
import "cordova-plugin-camera"

The import is working and npm install worked perfectly

Also vs code does not gives any problem with interfaces and classes but when i run the build the error shows up.

Thanks in advanced

**Comment by breautek** [comment] 2023-09-22 12:41
The "cordova" way of consuming the plugin is to not import anything since the symbols is available through the API standard namespaces, e.g: `window.navigator.camera.getPicture(...)`, as long as it's added via `cordova plugin add`.

I understand that CapacitorJS uses a build system and it does imports to enable different things, so if there's a problem with that, then it will probably best to ask Capacitor's community.

Closing as not a bug (with the camera plugin)

**Closed by breautek** 2023-09-22 12:41 UTC
