### ISSUE TITLE
Camera Plugin is not working on Google Pixel 2 With android 11

### ISSUE THREAD

**Issue by Ali54561** [apache/cordova-plugin-camera#734] opened 2021-05-31 11:43 UTC
# Bug Report

### What does actually happen?
When I go for camera access using plugin version 5.0.2, it is asking for permissions for Media and storage and then finished the process. Nothing happened.

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by WuglyakBolgoink** [comment] 2021-05-31 12:03
duplicate https://github.com/apache/cordova-plugin-camera/issues/673

**Comment by PieterVanPoyer** [comment] 2021-06-01 15:25
@Ali54561  Do you target  Android sdk 30? Or not? 
if this is the same issue as https://github.com/apache/cordova-plugin-camera/issues/673 . Please close this one, and provide a stacktrace or something else on issue https://github.com/apache/cordova-plugin-camera/issues/673 . 
If it is a different issue, please add a reproduction sample, a stacktrace or at least a little more info.

**Comment by Ali54561** [comment] 2021-06-01 15:44
Yes I target Android Sdk 30.
I am getting this error only on google pixel devices on which android 11 is installed. All other devices are working fine.

**Comment by PieterVanPoyer** [comment] 2021-06-01 19:09
> Yes I target Android Sdk 30.
> I am getting this error only on google pixel devices on which android 11 is installed. All other devices are working fine.

I am closing this as duplicate of https://github.com/apache/cordova-plugin-camera/issues/673 .
You can follow up on the state of the issue there, and provide more details, or test the fork https://github.com/apache/cordova-plugin-camera/pull/684 .

**Closed by PieterVanPoyer** 2021-06-01 19:09 UTC
Labels: info-needed, platform: android

**Comment by Ali54561** [comment] 2021-06-02 10:51
My app is not appearing on play store if I target 29. That's why I have to target API level 30 as a lot of my clients are using android 11.

**Comment by PieterVanPoyer** [comment] 2021-06-02 11:40
That's strange.
Target api level 30 should not be necessary yet to appear and submit to the playstore.

https://developer.android.com/distribute/best-practices/develop/target-sdk

![image](https://user-images.githubusercontent.com/33040889/120473801-b47d5700-c3a7-11eb-8aeb-7705996da570.png)
