### ISSUE TITLE
the application closes after taking a photo

### ISSUE THREAD

**Issue by intjose** [apache/cordova-plugin-camera#722] opened 2021-04-27 20:39 UTC
# Bug Report
When I take the photo it does not close, but until I give the popcorn to use it, the application closes, if I take the photo and give it back it does not close, only when I give the popcorn

## Information

only happens in a Motorola G8 Power lite
- Android 10
- 4 RAM
- 48GB free (Storage)

### Environment, Platform, Device
Android

### Version information
Last Version

## Checklist

- [X ] I searched for existing GitHub issues
- [ X] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by breautek** [comment] 2021-04-28 17:52
This can be normal behaviour on Android. Please see the Android quirk below.

> Android uses intents to launch the camera activity on the device to capture images, and on phones with low memory, the Cordova activity may be killed. In this scenario, the result from the plugin call will be delivered via the resume event. See the Android Lifecycle guide for more information. The pendingResult.result value will contain the value that would be passed to the callbacks (either the URI/URL or an error message). Check the pendingResult.pluginStatus to determine whether or not the call was successful.

https://github.com/apache/cordova-plugin-camera#android-quirks

Because the application goes into the background, the OS may kill the activity. When this happens, the Cordova application has to reload the webview. It's up to the developer to handle this scenario. Handling this is [explained here](https://cordova.apache.org/docs/en/dev/guide/platforms/android/index.html#retrieving-plugin-callback-results-cordova-android-510).

You can forcefully test this scenario by enabling "Don't keep activites" in the Android developer settings.

Closing as not a bug.

**Closed by breautek** 2021-04-28 17:52 UTC

**Comment by intjose** [comment] 2021-04-29 18:21
You will not have an example application?, I tried it but I still have the same problem, the problem is with the native camera of the device if I install another camera app it does not close and everything works fine, I just want an example code to see if I put something wrong
