### ISSUE TITLE
Illegal Argument Exception on Android

### ISSUE THREAD

**Issue by vlads63** [apache/cordova-plugin-camera#607] opened 2020-06-04 09:29 UTC
# Bug Report

## Problem
Getting Illegal Argument Exception on Android only when trying to take picture from camera
### What is expected to happen?
Camera should be started

### What does actually happen?
Illegal ArgumentException is thrown - no other explanation provided

## Information
The exception is thrown on Android only. The same code works fine in iOS
The code that reads from the library rather than from camera works well.
I am also pretty sure that the code used to work fine with older releases of the plugin.

### Command or Code
This is the Javascript code I am using:

		var me = this;
		var options = { 
		    	destinationType:    Camera.DestinationType.FILE_URI,
		    	correctOrientation: true,
		    	sourceType: Camera.PictureSourceType.CAMERA
		};
		navigator.camera.getPicture(
			function (fileURI) {
				me.uploadImage (fileURI, objectName, objectId, attrName, successCallback, errorCallback);
			}, 
			function (msg) {
				alert (msg);
				errorCallback ();
			}, 
			options
		);

The error function is executed with the msg = "Illegal argument exception"; No other information provided. I am not sure what to do with this,

### Environment, Platform, Device
Device: GT15907
Android: 5.0.1

### Version information
I am using Monaca build to create the apk file. I refer to the camera plugin like so:
 <plugin name="cordova-plugin-camera" spec="https://github.com/apache/cordova-plugin-camera"/>

**Comment by timbru31** [comment] 2020-06-04 10:01
Your issue is missing required version information. Without it, we can't help you.

**Comment by vlads63** [comment] 2020-06-04 11:36
Version information of the plugin? The latest one I presume. I refer to the plugin in the Monaca's build config.xml file like this:
 <plugin name="cordova-plugin-camera" spec="https://github.com/apache/cordova-plugin-camera"/>

**Comment by vlads63** [comment] 2020-06-04 11:37
plugin name="cordova-plugin-camera" spec="https://github.com/apache/cordova-plugin-camera"

**Comment by timbru31** [comment] 2020-06-04 11:39
Latest is not valid version, we need specific information. Please post both outputs of:
```
cordova info
npm ls cordova-plugin-camera
```

**Comment by vlads63** [comment] 2020-06-04 11:45
I don't know what you are referring to. I am just using your plugin in a Monaca build. I am referring to the plugin like I specified above with the "spec" attribute of the "plugin" XML statement pointing to the github site - see my post above. Where in a Monaca build can I see what you are asking me?

(as you can probably understand from my reply I am not an experienced Cordova developer, but this is not necessary, isn't it to use your plugin?

**Comment by vlads63** [comment] 2020-06-04 11:49
So, I guess, what I am saying - I don't know which version of the plugin Monaca is pulling in when I am referring to the plugin like I specified above. I presume it is the latest version - whatever it is,

**Comment by vlads63** [comment] 2020-06-04 11:50
If I need to refer to the plugin differently please specify how

**Comment by breautek** [comment] 2020-06-04 12:30
Most of us are likely not familiar with Monaca. The cordova CLI will by default use the latest version on npm, but I cannot say how to do it in Monaca. You will probably have to refer to their documentation.

> plugin name="cordova-plugin-camera" spec="https://github.com/apache/cordova-plugin-camera"

This makes it look like Monaca is using the master (dev) version of the plugin which isn't supported or recommended for production use. In fact, master is currently broken for android. The latest version that you should be using is `4.1.0`

You can try changing `spec="https://github.com/apache/cordova-plugin-camera"` to `spec="^4.1.0`, but this is just a guess, I'm unfamiliar with Monaca.

**Comment by vlads63** [comment] 2020-06-04 12:35
Thank you. I will try. Monaca is a terrific tool, by the way.

**Comment by jcesarmobile** [comment] 2020-06-04 15:36
it's a duplicate of https://github.com/apache/cordova-plugin-camera/issues/597

**Closed by jcesarmobile** 2020-06-04 15:36 UTC
Labels: bug, invalid, platform: android

**Comment by timbru31** [comment] 2020-06-04 18:10
That’s what I suspected, too, and asked multiple times for a concrete version 😂
