### ISSUE TITLE
4.2.0 not available on npm repo

### ISSUE THREAD

**Issue by Ultima2876** [apache/cordova-plugin-camera#639] opened 2020-08-01 05:39 UTC
https://www.npmjs.com/package/cordova-plugin-camera?activeTab=versions - latest version is the outdated (by a year) 4.1.0. This makes installation in cordova more difficult.

**Comment by erisu** [comment] 2020-08-01 07:14
Duplicate of https://github.com/apache/cordova-plugin-camera/issues/619

**Closed by erisu** 2020-08-01 07:14 UTC
