### ISSUE TITLE
The application stopped when taking a photo with the camera on the Moto Z² / Z¹ Play devices.

### ISSUE THREAD

**Issue by michaelbrq** [apache/cordova-plugin-camera#412] opened 2019-01-16 17:00 UTC
### The problem occurs on Motorola Z Play line devices, tests were performed on the Moto Z¹ Play and Moto Z² Play devices, using the configuration sourceType: Camera.PictureSourceType.CAMERA.

Scenario: The application stopped when taking a photo with the camera on the Moto Z² / Z¹ Play devices.

**Step by step to reproduce the error.**

**Step 1)**

- Action: Activate the camera via the 'cordova-plugin-camera' plugin using the 'sourceType: Camera.PictureSourceType.CAMERA' setting.
- Result: The default camera app opens.

**Step 2)**

- Action: Take a picture and accept it.
- Result: The cordova app is stopped and finished.

**Comment by mirko77** [comment] 2019-01-29 14:00
Same here on some devices running Android 8.0/8.1, targeting API 26

This is the log:

```

java.lang.RuntimeException: 
  at android.app.ActivityThread.deliverResults (ActivityThread.java:4295)
  at android.app.ActivityThread.handleSendResult (ActivityThread.java:4339)
  at android.app.ActivityThread.-wrap19 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1668)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6523)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:438)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:857)
Caused by: java.lang.SecurityException: 
  at android.os.Parcel.readException (Parcel.java:2005)
  at android.database.DatabaseUtils.readExceptionFromParcel (DatabaseUtils.java:183)
  at android.database.DatabaseUtils.readExceptionFromParcel (DatabaseUtils.java:135)
  at android.content.ContentProviderProxy.delete (ContentProviderNative.java:547)
  at android.content.ContentResolver.delete (ContentResolver.java:1636)
  at org.apache.cordova.camera.CameraLauncher.checkForDuplicateImage (CameraLauncher.java:1227)
  at org.apache.cordova.camera.CameraLauncher.cleanup (CameraLauncher.java:1193)
  at org.apache.cordova.camera.CameraLauncher.processResultFromCamera (CameraLauncher.java:595)
  at org.apache.cordova.camera.CameraLauncher.onActivityResult (CameraLauncher.java:805)
  at org.apache.cordova.CordovaInterfaceImpl.onActivityResult (CordovaInterfaceImpl.java:152)
  at org.apache.cordova.CordovaActivity.onActivityResult (CordovaActivity.java:358)
  at android.app.Activity.dispatchActivityResult (Activity.java:7290)
  at android.app.ActivityThread.deliverResults (ActivityThread.java:4291)

```

**Comment by snt1017** [comment] 2019-01-30 15:20
Same with Moto G5 plus, Moto G (5S), Moto E5 plus all with android 8.0 or 8.1

**Comment by mirko77** [comment] 2019-01-30 15:42
We are using version `2.4.1`, which is the version that gets installed with the version of Cordova we are using (6.5.0). We cannot upgrade Cordova as that will break other dependencies moreover the only plugin not working is the camera on some devices, since we started targeting API 26 (Google forced us to).

Any advice? We would not mind forking the repo and do manual changes to fix what it looks like a permission issue if we can get some insights on the issue

**Comment by snt1017** [comment] 2019-01-30 15:50
The problem is the plugin version, we update from `2.4.1` to `4.0.3` and now works correctly

**Comment by jcesarmobile** [comment] 2019-01-30 15:57
Closing as it doesn't seem a problem on 4.0.3, nor 4.1.0-dev

**Closed by jcesarmobile** 2019-01-30 15:57 UTC
